### PR TITLE
Upgrade to buildkit w/ performance fix. 

### LINKED ISSUE #4620: Engine fails, hangs or becomes really slow when several operations are chained
Some users (cc @cpuguy83 ) have observed that when chaining  several `WithMountedDirectory` calls, sometimes the engine becomes extremely slow or completely unresponsive. 

Discord thread: https://discord.com/channels/707636530424053791/1075544944388882522

@cpuguy83 managed to come up with a simple repro here.

Repro snippet: https://gist.github.com/cpuguy83/b61f22d05fd05a6407008d944f5858f4

cc @sipsma

### PR DESCRIPTION
**Pull request by sipsma**
Upgrades us to buildkit with this fix: https://github.com/moby/buildkit/pull/3732

Fixes #4620 

I also realized there's a simpler way to build the buildctl bin from our go.mod version which enables us to only have to specify the buildkit dependency version in one place, so I included that here too.

### CODE REVIEW

File: core/integration/container_test.go [hunk 1]
```diff
@@ -2935,11 +2935,11 @@ func TestContainerInsecureRootCapabilites(t *testing.T) {
...
-	require.Contains(t, out, "CapInh:\t0000003fffffffff")
-	require.Contains(t, out, "CapPrm:\t0000003fffffffff")
-	require.Contains(t, out, "CapEff:\t0000003fffffffff")
-	require.Contains(t, out, "CapBnd:\t0000003fffffffff")
-	require.Contains(t, out, "CapAmb:\t0000003fffffffff")
+	require.Contains(t, out, "CapInh:\t0000001fffffffff")
+	require.Contains(t, out, "CapPrm:\t0000001fffffffff")
+	require.Contains(t, out, "CapEff:\t0000001fffffffff")
+	require.Contains(t, out, "CapBnd:\t0000001fffffffff")
+	require.Contains(t, out, "CapAmb:\t0000001fffffffff")
```
Comment (vito) [inline core/integration/container_test.go:2942]: I guess Buildkit drops some capabilities by default now?

File: internal/mage/engine.go [hunk 2]
```diff
@@ -445,12 +416,11 @@ func buildctlBin(c *dagger.Client, arch string) *dagger.File {
...
 		WithEnvVariable("GOARCH", arch).
-		WithMountedDirectory("/app", c.Git(buildkitRepo).Branch(buildkitRef).Tree()).
+		WithEnvVariable("GOBIN", "/app/bin").
 		WithExec([]string{
-			"go", "build",
-			"-o", "./bin/buildctl",
+			"go", "install",
 			"-ldflags", "-s -w",
-			"/app/cmd/buildctl",
+			"github.com/moby/buildkit/cmd/buildctl",
```
Comment (vito) [inline internal/mage/engine.go:423]: nice!

**Review by vito — APPROVED** [review]

**Comment by sipsma** [comment]
Ugh my simplification to the CI caused a failure here: https://github.com/dagger/dagger/actions/runs/4494928110/jobs/7908013455?pr=4817#step:4:452

I'll see if there's an easy fix or just take that commit out for now since it was just nice to have

File: core/integration/container_test.go (hunk 1 above)
Comment (sipsma) [reply core/integration/container_test.go:2942]: Yeah I'm not sure exactly why this changed, probably a transitive dependency on buildkit, but from `capsh --decode=0000001fffffffff` it looks like `cap_audit_read` is not present now.

That capability will "allow reading the audit log via a multicast netlink socket", which to my knowledge is very obscure, so I don't think it's worth caring about right now.

Comment (sipsma) [reply core/integration/container_test.go:2942]: Well now the test failed in CI because there it apparently is still `0000003fffffffff` ??? 

I don't know why this is different between my box and CI but I think I'll just update this test to decode the capabilities and assert that the major ones like cap_sys_admin are there.

**Comment by sipsma** [comment]
Fixed the go install error, thanks for the suggestion @vito! Also made the capability test consistent between my box and CI (not sure that's actually related to the upgrade actually, I have a pretty new kernel due to rebuilding my dev box recently so it might be that). Merging
