### PR TITLE
fix mount propagation causing repeated runs

### LINKED ISSUE #3551: 🐞 Odd container behavior with exec / multiple withMountedDirectory
### What is the issue?

The following code executes but provides unexpected logs / output. Other similar use cases error due to missing files due to same issue. This may be something very simple (haven't used golang in many years) but seems like there may be an underlying issue with the execution engine.

I would expect this code to run the `ls` command twice, one time showing the two mounted directories, one time showing the root output. Instead in the logs I see `ls` with d1 and d2 (expected), an `ls` with just d1 (??), and then an `ls` with the root fs. This causes issues if the first ls is changed to `ls /example/d2` as it will error the whole pipeline due to missing path.

```golang
workdir := client.Host().Workdir()
d1, err := workdir.Read().Directory("dir1/").ID(ctx)
if err != nil {
    return err
}
d2, err := workdir.Read().Directory("dir2/").ID(ctx)
if err != nil {
    return err
}

build := client.Container().From("alpine:latest").
    WithMountedDirectory("/example/d1", d1).
    WithMountedDirectory("/example/d2", d2)

build = build.Exec(dagger.ContainerExecOpts{
    Args: []string{"ls", "/example"},
})
_, err = build.ExitCode(ctx)
if err != nil {
    return err
}
build = build.Exec(dagger.ContainerExecOpts{
    Args: []string{"ls", "/"},
})
_, err = build.ExitCode(ctx)
if err != nil {
    return err
}
```

I was able to get the same functionality working fine by using `fs, err := build.FS().WithDirectory(d1, "/example/d1").WithDirectory(d2, "/example/d2").ID(ctx); build = build.WithFS(fs);` so conceptually don't think I'm doing anything wrong.

### Log output

```
#1 resolve image config for docker.io/library/alpine:latest
#1 DONE 0.4s

#2 mkfile /Dockerfile
#2 DONE 0.0s

#3 mkfile /main.go
#3 CACHED

#4 [internal] load metadata for docker.io/library/golang:1.18.2-alpine
#4 DONE 0.1s

#5 local://__dagger_workdir_/home/plaisted/source/OSD.PJI-Temporary/repro
#5 DONE 0.0s

#6 local://__dagger_workdir_/home/plaisted/source/OSD.PJI-Temporary/repro
#6 transferring __dagger_workdir_/home/plaisted/source/OSD.PJI-Temporary/repro: 309B done
#6 DONE 0.0s

#7 [build 1/6] FROM docker.io/library/golang:1.18.2-alpine@sha256:4795c5d21f01e0777707ada02408debe77fe31848be97cf9fa8a1462da78d949
#7 resolve docker.io/library/golang:1.18.2-alpine@sha256:4795c5d21f01e0777707ada02408debe77fe31848be97cf9fa8a1462da78d949 0.0s done
#7 DONE 0.0s

#8 [build 3/6] RUN apk add --no-cache file git
#8 CACHED

#9 [build 4/6] RUN go mod init go.dagger.io/dagger/shim/cmd
#9 CACHED

#10 [build 2/6] WORKDIR /src
#10 CACHED

#11 [build 5/6] COPY . .
#11 CACHED

#12 [build 6/6] RUN CGO_ENABLED=0 go build -o /_shim -ldflags '-s -d -w' .
#12 CACHED

#13 [stage-1 1/1] COPY --from=build /_shim /_shim
#13 CACHED

#14 mkdir /meta
#14 CACHED

#15 copy / /
#15 DONE 0.0s

#16 docker-image://docker.io/library/alpine:latest
#16 resolve docker.io/library/alpine:latest
#16 resolve docker.io/library/alpine:latest 0.1s done
#16 CACHED

#17 copy / /
#17 CACHED

#18 ls /example
#18 0.157 d1
#18 0.157 d2
#18 DONE 0.2s

#1 resolve image config for docker.io/library/alpine:latest
#1 DONE 0.5s

#4 [internal] load metadata for docker.io/library/golang:1.18.2-alpine
#4 DONE 0.4s

#19 ls /example
#19 0.172 d1
#19 DONE 0.2s

#20 ls /
#20 0.105 _shim
#20 0.105 bin
#20 0.105 dagger
#20 0.105 dev
#20 0.105 etc
#20 0.105 example
#20 0.105 home
#20 0.105 lib
#20 0.105 media
#20 0.105 mnt
#20 0.105 opt
#20 0.105 proc
#20 0.105 root
#20 0.105 run
#20 0.105 sbin
#20 0.105 srv
#20 0.105 sys
#20 0.105 tmp
#20 0.105 usr
#20 0.105 var
#20 DONE 0.1s
#0 0.148 d1
#0 0.148 d2
#18 DONE 0.2s

#1 resolve image config for docker.io/library/alpine:latest
#1 DONE 0.4s

#4 [internal] load metadata for docker.io/library/golang:1.18.2-alpine
#4 DONE 0.4s

#19 ls /example
#0 0.135 d1
#19 DONE 0.2s

#20 ls /example
#0 0.104 d1
#0 0.104 d2
#20 DONE 0.1s
```

### Steps to reproduce

* Mount two directories
* Run multiple exec commands and observe logs output

### Dagger version

dagger v0.3.1

### OS version

Ubuntu-20.04

### PR DESCRIPTION
**Pull request by vito**
fixes #3551

* propagate mounts from the result of running the command with every mount, rather than one at a time as we iterate, which meant each mount technically had a different llb state.
* remove stacking semantics as Buildkit currently assumes mount targets are unique (see second commit message)

### CODE REVIEW

File: core/container.go [hunk 1]
```diff
@@ -145,6 +145,27 @@ func (mnt ContainerMount) SourceState() (llb.State, error) {
...
+type ContainerMounts []ContainerMount
+
+func (mnts ContainerMounts) With(newMnt ContainerMount) ContainerMounts {
+	mntsCp := make(ContainerMounts, len(mnts))
+	copy(mntsCp, mnts)
+
+	var replaced bool
+	for i, mnt := range mntsCp {
+		if mnt.Target == newMnt.Target {
+			mntsCp[i] = newMnt
```
Comment (vito) [inline core/container.go:157]: Might be better to remove from the found index and append to the end instead to match stacking semantics, i.e. so later mounts to subpaths of the target don't mount "over" it. Not sure if that's what'll actually happen though.

**Review by sipsma — APPROVED** [review]
LGTM, one comment about a possible test to add to verify behavior.

It seems like if we modified upstream `client/llb` to instead call `sort.SliceStable` on exec state mounts then we could probably retain the stacking behavior (?), but this case of stacked vs. non-stacked is obscure enough that I don't think it matters right now.

File: core/container.go (hunk 1 above)
Comment (vito) [reply core/container.go]: Oh right, so it doesn't really matter where we insert.

Added a test that checks that when adding mount B above, mount A is removed and we can still add mount C after. I think this is more correct than the current behavior which allows it to stick around. But we're really splitting hairs, I'd be equally happy to remove this and leave the behavior undefined until someone has a use case. :shrug:

**Comment by vito** [comment]
> It seems like if we modified upstream client/llb to instead call sort.SliceStable on exec state mounts then we could probably retain the stacking behavior (?), but this case of stacked vs. non-stacked is obscure enough that I don't think it matters right now.

@sipsma Yeah, I think so, but at this point I'm a little worried about any other areas in Buildkit that assume mounts are unique. Agree that it seems sufficiently edge-casey to not worry about going above and beyond.

This is ready for another look, I tweaked the replacing semantics to simulate more aspects of stacking (basically remove /mnt/foo when mounting over /mnt).

**Review by sipsma — APPROVED** [review]
