### PR TITLE
fix: make workspace module loading opt-in

### LINKED ISSUE #12982: workspace modules should be opt-in, not auto-loaded by default
## Problem

Since [workspace: plumbing & compat](https://github.com/dagger/dagger/pull/11995), the engine auto-loads modules from the current workspace by default. That means a client that never explicitly loads modules can still have its schema changed based on its current working directory.

This is especially dangerous when an auto-loaded module is served with `entrypoint: true` and defines a function that conflicts with a core Query field. In that case, a plain core API call can silently route through the workspace module instead.

For example, if a workspace module `foo` is auto-loaded as an entrypoint and defines `container()`, then a client doing:

`dagger.Connect().Container().From("alpine")`

may actually be calling `foo.container()` instead of core `Query.container`.

That is not what users should expect. Merely running a client inside a workspace should not silently change the meaning of core API calls.

This can also trigger unexpected side effects from module constructors and defaults. In one concrete case, a plain `container` call ended up invoking an auto-loaded workspace module constructor, which resolved a `+defaultPath` argument and triggered filesync, even though the client never explicitly loaded or called that module.

This is too disruptive to be opt-out. It should be opt-in.

## Solution

Workspace module loading should be opt-in.

Add `LoadWorkspaceModules bool`, defaulting to `false`.

By default, `dagger.Connect()` should expose only the core API. Workspace modules should only be loaded when the client explicitly requests that behavior.

`SkipWorkspaceModules` should stop being part of the public design. It can remain supported as a hidden legacy compatibility input, normalized once at the boundary into `LoadWorkspaceModules`. If both `SkipWorkspaceModules` and `LoadWorkspaceModules` are set, that should be an error.

### PR DESCRIPTION
**Pull request by shykes**
## Summary
- make workspace module loading opt-in by introducing `LoadWorkspaceModules`
- default plain connections to the core API only
- keep `SkipWorkspaceModules` as a legacy compatibility input at the boundary

Closes #12982.

## Verification
- targeted Go tests for engine and Go SDK option/session wiring
- Python syntax check
- Rust formatting check

### CODE REVIEW

File: core/integration/client_generator_test.go [hunk 1]
```diff
@@ -394,6 +394,7 @@ main()
 			generator string
 			callCmd   []string
 			setup     dagger.WithContainerFunc
+			runSetup  dagger.WithContainerFunc
```
Comment (grouville) [inline core/integration/client_generator_test.go:397]: Ok, so this test suite verifies:

> that given a _go_ && _ts_ module on which we install a client module, with `dagger client install XXX`, can we actually run it, either via a `dagger run` or directly with a `go run` ?

With the opt-in module loading, that this PR introduces, we now have a divergence: 
1. a client ran with `go run main.go` and with the option ` dagger.Connect(ctx,dagger.WithLoadWorkspaceModules())` can opt-in to module loading
2. a client ran with `dagger run go run main.go` is however attached to the dagger run session opened, thus the `dagger.Connect(ctx,dagger.WithLoadWorkspaceModules())` from the code is not followed

The solution introduced in a follow-up commit of this PR is to add a hidden flag to the `dagger run` CLI to optionally opt-in when running `dagger run` commands

Given that it's a hidden feature, it does mean that users:
1. relying on `dagger run` to run their go package wrapping their dagger go sdk code
2. relying on the client generator feature, to still access modules

will break

However, as it's a niche use-case and a fallback is introduced in my commit, it's ok, IMO

**Review by tiborvass — APPROVED** [review]
let's gooo
