### PR TITLE
fix interactive TUI

### LINKED ISSUE #5662: 🐞 Interactive TUI seems broken since Dagger 0.8.x
### What is the issue?

I upgraded from Dagger 0.6 to Dagger 0.8. The experimental dagger interactive terminal UI is now broken. As a developer, this interface is really useful and I would like to keep it ;)

### Log output

```
Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 8 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:440 +0x8c
panic({0x1015f6ba0, 0x1020161f0})
        /usr/local/go/src/runtime/panic.go:890 +0x258
github.com/dagger/dagger/internal/tui.(*Details).SetItem(...)
        /app/internal/tui/details.go:37
github.com/dagger/dagger/internal/tui.Model.processUpdate({0x140005a7b70, {0x10179f7e0, 0x1400002a780}, 0x1400002a840, 0x1400002a870, 0x1400002a8a0, 0x14000155900, {{0x0, 0x0}, 0xcb, ...}, ...}, ...)
        /app/internal/tui/model.go:302 +0x61c
github.com/dagger/dagger/internal/tui.Model.Update({0x140005a7b70, {0x10179f7e0, 0x1400002a780}, 0x1400002a840, 0x1400002a870, 0x1400002a8a0, 0x14000155900, {{0x1017b64e0, 0x14000118000}, 0xcb, ...}, ...}, ...)
        /app/internal/tui/model.go:138 +0x4c0
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0x140002dc180, {0x1017a7450?, 0x1400058ee00?}, 0x0?)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:373 +0x5d8
github.com/charmbracelet/bubbletea.(*Program).Run(0x140002dc180)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:503 +0x74c
main.interactiveTUI.func1()
        /app/cmd/dagger/engine.go:136 +0x28
created by main.interactiveTUI
        /app/cmd/dagger/engine.go:135 +0x1c8
```

### Steps to reproduce

```
env _EXPERIMENTAL_DAGGER_INTERACTIVE_TUI=1 dagger run ts-node --esm build.mjs
```

The content build.mjs is a "default" node setup with npm install and npm test. Pipeline is working fine without the env var.

### SDK version

@dagger.io/dagger 0.8.4

### OS version

macOS 13.2

### PR DESCRIPTION
**Pull request by vito**
It wasn't able to cope with the new 'init' vertex that we create while initializing, and it wasn't transitioning to `COMPLETED` anymore.

Along the way, also remove the redundant 'Duration' status info now that Progrock displays timing info natively in its UI. Also use Pipeliner to dedupe vertices since that was pretty confusing before.

fixes #5662

### CODE REVIEW

File: cmd/dagger/engine.go [hunk 1]
```diff
@@ -195,13 +196,7 @@ func inlineTUI(
 		return err
 	}
 	defer sess.Close()
-	before := time.Now()
 	err = fn(ctx, sess)
-	program.Send(progrock.StatusInfoMsg{
-		Name:  "Duration",
-		Value: time.Since(before).Truncate(time.Millisecond).String(),
-		Order: 3,
-	})
```
Comment (vito) [inline cmd/dagger/engine.go:204]: This isn't needed now that Progrock shows a timer by default. Note the redundant timing info:

image

File: internal/tui/item.go [hunk 2]
```diff
@@ -219,259 +218,3 @@ func (i *Item) tasksView() string {
 
 	return strings.Join(tasks, "\n")
 }
-
```
Comment (vito) [inline internal/tui/item.go:222]: Sorry for the noise, I don't think anything actually changed here, just wanted to split it out.

File: internal/tui/model.go [hunk 3]
```diff
@@ -347,16 +350,41 @@ func (m Model) processUpdate(msg *progrock.StatusUpdate) (tea.Model, tea.Cmd) {
 	return m, tea.Batch(cmds...)
 }
 
+func (m Model) addToFirstGroup(id string) {
```
Comment (vito) [inline internal/tui/model.go:353]: A side fix; I recently changed it to include duplicates vertices, but I think it was ultimately just confusing DX, so now it just picks the first pipeline path that the vertex is seen in, the same way the Cloud telemetry flow works.

File: telemetry/pipeliner.go [hunk 4]
```diff
@@ -45,12 +45,12 @@ type PipelinedVertex struct {
 	Pipelines []pipeline.Path
 }
 
-func (t *Pipeliner) WriteStatus(ev *progrock.StatusUpdate) error {
```
Comment (vito) [inline telemetry/pipeliner.go:48]: Another side fix; there was no need for this type to be a `progrock.Writer`, and removing the `error` return value makes the caller's lives easier.

**Comment by vito** [comment]
Growing scope a bit to bump to Progrock v0.10 which cleans up the clumsy "multiple root groups" situation by forcing every root group to have the same ID.

**Comment by vito** [comment]
Manually verified root group labels are making their way to Cloud even with the additional 'root group' for client initializing.

cc @marcosnils - tl;dr Progrock now enforces that all "root groups" (i.e. the outermost group for every Recorder) have the exact same ID. Nothing should break but let me know if you see anything strange!

I temporarily updated the `TestClientSendsLabelsInTelemetry` integration test to log the events sent to Cloud, just to take a peek, and here's what you can expect - note the first Op has no Labels on the root pipeline, and the later ones do:

```
    engine_test.go:247: received events:
        {"v":"2023-02-28.01","ts":"2023-08-28T18:29:49.619491328Z","run_id":"0b4342b9-a822-421d-8035-137254f1a426","type":"op","payload":{"op_id":"starting-engine","op_name":"connect","pipeline":[{"name":""},{"name":"init","weak":true}],"internal":false,"inputs":null,"started":"2023-08-28T18:29:49.619402409Z","completed":null,"cached":false,"error":""}}
        {"v":"2023-02-28.01","ts":"2023-08-28T18:29:49.619491328Z","run_id":"0b4342b9-a822-421d-8035-137254f1a426","type":"op","payload":{"op_id":"starting-engine","op_name":"connect","pipeline":[{"name":""},{"name":"init","weak":true}],"internal":false,"inputs":null,"started":"2023-08-28T18:29:49.619402409Z","completed":null,"cached":false,"error":""}}
        {"v":"2023-02-28.01","ts":"2023-08-28T18:29:49.870300473Z","run_id":"0b4342b9-a822-421d-8035-137254f1a426","type":"op","payload":{"op_id":"sha256:139a643d0a7ab1c0a2d18773efafbea882afd8bde41814d9b042b1fc33eab058","op_name":"defaultPlatform","pipeline":[{"name":"","labels":[{"name":"dagger.io/git.ref","value":"3975a48a43fc6eb84284c91c18474d6083149fc1"},{"name":"dagger.io/git.author.name","value":"Tiësto User"},{"name":"dagger.io/git.author.email","value":"test@example.com"},{"name":"dagger.io/git.committer.name","value":"Tiësto User"},{"name":"dagger.io/git.committer.email","value":"test@example.com"},{"name":"dagger.io/git.title","value":"init test repo"},{"name":"dagger.io/git.branch","value":"main"},{"name":"dagger.io/engine","value":"7vfu121b7rug6.vfk39ri8sqroc.dagger.local"}]}],"internal":true,"inputs":null,"started":"2023-08-28T18:29:49.868720791Z","completed":null,"cached":false,"error":""}}
        {"v":"2023-02-28.01","ts":"2023-08-28T18:29:49.870300473Z","run_id":"0b4342b9-a822-421d-8035-137254f1a426","type":"op","payload":{"op_id":"sha256:139a643d0a7ab1c0a2d18773efafbea882afd8bde41814d9b042b1fc33eab058","op_name":"defaultPlatform","pipeline":[{"name":"","labels":[{"name":"dagger.io/git.ref","value":"3975a48a43fc6eb84284c91c18474d6083149fc1"},{"name":"dagger.io/git.author.name","value":"Tiësto User"},{"name":"dagger.io/git.author.email","value":"test@example.com"},{"name":"dagger.io/git.committer.name","value":"Tiësto User"},{"name":"dagger.io/git.committer.email","value":"test@example.com"},{"name":"dagger.io/git.title","value":"init test repo"},{"name":"dagger.io/git.branch","value":"main"},{"name":"dagger.io/engine","value":"7vfu121b7rug6.vfk39ri8sqroc.dagger.local"}]}],"internal":true,"inputs":null,"started":"2023-08-28T18:29:49.868720791Z","completed":null,"cached":false,"error":""}}
```

I think the proper behavior here is probably to just roll up all the labels ever seen for the root group, which might already be what Cloud does.

As a knock-on effect this might mean users now see the initializing/connecting group + vertex in the Cloud UI. Not sure if that's already happening, but it's definitely happening with this change ([example](https://alpha.dagger.cloud/runs/75da12df-8a3e-4162-a354-8d4109cb3a97)). It matches the TUI so this isn't necessarily a bad thing. We could mark it "internal" if we don't want it shown in either, but that's tricky because we at least want to show it in the TUI while the initialization is happening in case it's taking a long time.
