### PR TITLE
setup nested session in the shim instead of the executor

### LINKED ISSUE #4206: Fix serve of nested session from shim
Realized as I was chatting about something that the serving of a nested session needs to occur inside the `shim()` func, whereas today it's in the `setupBundle()` func: https://github.com/sipsma/dagger/blob/6272f1919c78abb46c83fe5e1e460a71ef7a9980/cmd/shim/main.go#L207-L207

Otherwise, the local dirs referenced by the nested session will be incorrect and outside the container.

The fix is simple but going to add some explicit tests for this. It got missed because previously our test coverage of nested sessions happened implicitly by using dagger-in-dagger to run all our CI tests, but since we moved away from that it's not covered anymore

### PR DESCRIPTION
**Pull request by marcosnils**
fixes #4206

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

**Comment by marcosnils** [comment]
checking tests.

File: core/integration/dind_test.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+		}
+	}
+
+	err := testutil.Query(
+		`
+{
+  container {
+    from(address: "golang") {
+      withWorkdir(path: "/usr/src/app") {
+        withExec(args: ["sh", "-c", "go mod init test && go get dagger.io/dagger@main"]) {
```
Comment (sipsma) [inline core/integration/dind_test.go:35]: I think this will create a catch 22 if we make any backwards incompatible changes to the session interface since we will be testing the previous push to main against the dev engine here.

I think we can just load in the go sdk from `../../sdk/go` and setup a replace to use that instead

File: cmd/shim/main.go [hunk 2]
```diff
@@ -204,10 +213,19 @@ func setupBundle() int {
...
-	if err != nil {
-		fmt.Printf("Error toggling nesting: %v\n", err)
-		return 1
+checkenv:
+	for _, env := range spec.Process.Env {
+		switch {
+		case strings.HasPrefix(env, "_DAGGER_ENABLE_NESTING="):
+			// mount buildkit sock since it's nesting
+			spec.Mounts = append(spec.Mounts, specs.Mount{
+				Destination: "/run/buildkit/buildkitd.sock",
```
[the remark this answers is not in the document]
Comment (marcosnils) [reply cmd/shim/main.go:222]: > so lets just put this at /.runner.sock for now (it's temporary anyways, follow ups should be able move the shim entirely out of the container)

will dagger find the socket if it's located at that dir?

File: core/integration/dind_test.go (hunk 1 above)
Comment (marcosnils) [reply core/integration/dind_test.go:35]: > I think we can just load in the go sdk from `../../sdk/go` and setup a replace to use that instead

I guess that instead of doing this I can just use an `alpine` container and run a `curl` against the API. WDYT? Tests will be faster also since we don't need to pull the `golang` image also

Comment (sipsma) [reply core/integration/dind_test.go:35]: Yep that works too!

File: cmd/shim/main.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (sipsma) [reply cmd/shim/main.go:222]: We would just need to update `RunnerHost` in the engine start config on line 310 of the shim too

[the remark this answers is not in the document]
Comment (marcosnils) [reply cmd/shim/main.go:222]: :+1:

File: core/integration/dind_test.go (hunk 1 above)
Comment (marcosnils) [reply core/integration/dind_test.go:35]: Strange.. I tried changing the query to: 

```
{
  container {
    from(address: "alpine") {
      withExec(args: ["apk", "add", "curl"]) {
        withExec(args: ["sh", "-c", """
curl \
-u $DAGGER_SESSION_TOKEN: \
-H "content-type:application/json" \
-d '{"query":"{host{directory(path:\".\"){entries}}}"}' $DAGGER_SESSION_URL/query

        """], experimentalPrivilegedNesting: true) {
          stdout
        }
        }
    }
  }
}```

and I'm getting the same `context canceled` error as before :thinking:

Comment (sipsma) [reply core/integration/dind_test.go:35]: @marcosnils The new container you're using defaults the current work dir to `/`, so that `.` path is trying to load up the whole rootfs, including special filesystems like /proc which might result in the shim reading its own open file descriptors and other weird stuff. It seems to work as expected if you specify a normal directory like `/root` or similar.

The `context canceled` error is obviously not very helpful here though, I'm not sure why that's what we get. My best guess is something weird happening w/ proc or sys. I'll poke a bit and create a follow up issue if nothing else. But that can be a separate issue, shouldn't block this.

**Comment by marcosnils** [comment]
Wow, awesome Erik! Wondering how you figured out such specific case :)

Em sex., 23 de dez. de 2022 23:04, Erik Sipsma ***@***.***>
escreveu:

**Review by sipsma — APPROVED** [review]
