### PR TITLE
filter out useless commandConn.CloseWrite warning message

### LINKED ISSUE #1689: Do not show commandconn WARN messages on the first dagger run
When `dagger` runs for the first time against a local Docker Engine, it shows the following `WARN` messages:

```
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseRead: commandconn: failed to wait: signal: terminated
WARN[0002] commandConn.CloseWrite: commandconn: failed to wait: signal: terminated
```

This is a bad first experience, and we should improve our first impression.

Point-in-time capture of the latest `dagger` dev version behaviour (pre `0.2.0-beta.1`)

image

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #1689

encounter this issue while making a review for the GitHub Action: https://github.com/dagger/dagger-for-github/pull/47

```
  /opt/hostedtoolcache/dagger/0.2.6/x64/dagger do test --log-format plain
  time="2022-04-13T00:09:40Z" level=warning msg="commandConn.CloseWrite: commandconn: failed to wait: signal: terminated"
  time="2022-04-13T00:09:40Z" level=warning msg="commandConn.CloseRead: commandconn: failed to wait: signal: terminated"
  time="2022-04-13T00:09:40Z" level=warning msg="commandConn.CloseWrite: commandconn: failed to wait: signal: terminated"
  12:09AM INF actions.test.script._write | computing
  12:09AM INF actions.test.image._dag."0"._op | computing
  12:09AM INF actions.test.script._write | completed    duration=0s
```

for now filter out `commandConn.CloseWrite` warning message that can occur when dagger runs for the first time. this should be fixed upstream: https://github.com/docker/cli/blob/3fb4fb83dfb5db0c0753a8316f21aea54dab32c5/cli/connhelper/commandconn/commandconn.go#L203-L214

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

File: cmd/dagger/cmd/root.go [hunk 1]
```diff
@@ -21,6 +23,16 @@ var rootCmd = &cobra.Command{
 }
 
 func init() {
+	// filter out useless commandConn.CloseWrite warning message that can occur
+	// when dagger runs for the first time. This should be fixed upstream:
+	// unreachable: "commandConn.CloseWrite: commandconn: failed to wait: signal: killed"
+	// https://github.com/docker/cli/blob/3fb4fb83dfb5db0c0753a8316f21aea54dab32c5/cli/connhelper/commandconn/commandconn.go#L203-L214
+	logrus.AddHook(logutil.NewFilter([]logrus.Level{
```
Comment (marcosnils) [inline cmd/dagger/cmd/root.go:30]: Can't we achieve the same using zerolog hooks? https://github.com/rs/zerolog#hooks

So we don't pull another dependency

Comment (crazy-max) [reply cmd/dagger/cmd/root.go:30]: I would have liked to but upstream it using logrus unfortunately: https://github.com/docker/cli/blob/3fb4fb83dfb5db0c0753a8316f21aea54dab32c5/cli/connhelper/commandconn/commandconn.go#L203-L214 so don't think we can workaround that.

Comment (crazy-max) [reply cmd/dagger/cmd/root.go:30]: Also it's a transient dep so currently used anyway I think: https://github.com/dagger/dagger/blob/464c7ad708ba93e15df08d71ab3f552539b243f6/go.sum#L1313-L1314

**Review by aluzzardi — APPROVED** [review]
Thank you @crazy-max!

Much appreciated :)

File: cmd/dagger/cmd/root.go (hunk 1 above)
Comment (aluzzardi) [reply cmd/dagger/cmd/root.go:30]: 👍
