### PR TITLE
Avoid duplicate StringSlices when parsing flags

### LINKED ISSUE #2240: 🐞 Dagger 0.2.7 hit buildkit multiple cache exports issue
### What is the issue?

When you use, like in gitlab documentation example, the dagger cache arguments buildkit throws an error related with multiple cache exports.

### Log output

WARN[0000] local cache import at .dagger-cache not found due to err: could not read .dagger-cache/index.json: open .dagger-cache/index.json: no such file or directory 
WARN[0000] local cache import at .dagger-cache not found due to err: could not read .dagger-cache/index.json: open .dagger-cache/index.json: no such file or directory 
server.go:647: http2: server connection error from localhost: connection error: PROTOCOL_ERROR
10:35AM FTL system | failed to execute plan: specifying multiple cache exports is not supported currently

### Steps to reproduce

I created a [poc](https://github.com/Alvise88/dagger-0.2.7-buildkit-issue)

### Dagger version

0.2.7

### OS version

Docker Desktop on Windows 10

### PR DESCRIPTION
**Pull request by marcosnils**
Handles the action flags parsing separately so we don't have to call
`Parse()` multiple times on the main FlagSet as it has some issues with
StringArrays as described here https://github.com/spf13/pflag/issues/244

Also fixes #2240 

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

cc @jlongtine

### CODE REVIEW

File: cmd/dagger/cmd/do.go [hunk 1]
```diff
@@ -85,13 +85,9 @@ var doCmd = &cobra.Command{
 		}
 
 		actionFlags := getActionFlags(action)
-
+		actionFlags.Parse(args)
```
Comment (TomChv) [inline cmd/dagger/cmd/do.go:88]: What's the diff between what we tried and now? We are still parsing flags two time

**Review by TomChv — APPROVED** [review]
Hey 👋 

I tested with repro case from #2240 and with an option in addition and that works well!

```shell
dagger do test --cache-to type=local,mode=max,dest=toto --cache-from type=local,src=toto --foo test
Changed: foo: test
WARN[0000] local cache import at toto not found due to err: could not read toto/index.json: open toto/index.json: no such file or directory 
[✔] actions.test.script                                                                                                                                           0.0s
[✔] actions                                                                                                                                                       0.0s
[✔] actions.test                                                                                                                                                  0.1s
[✔] actions.test.export                                                                                                                                           0.0s
[✔] client.filesystem."output.txt".write                                                                                                                          0.0s

cat output.txt
test!

ls toto 
blobs      index.json ingest
``` 

<details>
<summary>Click to see my plan</summary>

```cue
package main

import (
	"dagger.io/dagger"
	"universe.dagger.io/alpine"
	"universe.dagger.io/bash"
)

dagger.#Plan & {
	client: filesystem: "output.txt": write: contents: actions.test.export.files["/hello.txt"]

	actions: {
		_image: alpine.#Build & {
			packages: bash: {}
		}

		test: {
			bash.#Run & {
				input: _image.output
				script: contents: "echo \(test.foo)! > /hello.txt"
				export: files: "/hello.txt": string
				always: true
			}

			foo: string
		}

	}
}

```

</details>

So I think it's ready for a merge after @jlongtine validate the code

File: cmd/dagger/cmd/do.go (hunk 1 above)
Comment (marcosnils) [reply cmd/dagger/cmd/do.go:88]: This works because we're only parsing the `actionFlags` FlagSet that *only* handles the action flags. Before we were calling `cmd.Flags().Parse()` which was re-parsing all the arguments twice and therefore duplicating the `--cache-to` value by triggering https://github.com/spf13/pflag/issues/244. Does it make sense?

Comment (TomChv) [reply cmd/dagger/cmd/do.go:88]: Sure! Thank you :D

File: cmd/dagger/cmd/do.go [hunk 2]
```diff
@@ -85,13 +85,9 @@ var doCmd = &cobra.Command{
...
 		cmd.Flags().AddFlagSet(actionFlags)
 
-		cmd.Flags().ParseErrorsWhitelist = pflag.ParseErrorsWhitelist{
-			UnknownFlags: false,
-		}
-		err = cmd.Flags().Parse(args)
 		if err != nil {
```
Comment (morlay) [inline cmd/dagger/cmd/do.go:91]: Does the error from `err = actionFlags.Parse(args)`?

`cmd.Flags().AddFlagSet(actionFlags)` may be after this err handler?

Comment (marcosnils) [reply cmd/dagger/cmd/do.go:91]: > Does the error from `err = actionFlags.Parse(args)`?

We shouldn't check the error here because `actionFlags.parse(args)` will most likely return an error since it will complain about `not defined arguments`. Hence, using a `ContinueOnError` parsing strategy.

**Comment by jlongtine** [comment]
@marcosnils This all looks pretty good to me. One concern I have is that we never validate the flags. So our users could pass a flag that doesn't exist and we won't display an error on that. I understand why... but I'm a bit concerned about the DX on it. 

@shykes thoughts on this?

**Review by jlongtine — APPROVED** [review]
Let's create an issue for the lack of flag validation, but good beyond that.
