### PR TITLE
Configurable shutdown timeout using _EXPERIMENTAL_DAGGER_SHUTDOWN_TIMEOUT #11328

### LINKED ISSUE #11328: 🐞 Dagger "close dagger session" fails when using _EXPERIMENTAL_DAGGER_CACHE_CONFIG
### What is the issue?

I have a simple module which builds an image and publishes it to ECR. I've also configured it to export the layer cache using `_EXPERIMENTAL_DAGGER_CACHE_CONFIG`. However, with this configured, it appears that the cache exporter exceeds the timeout window, causing the call to fail with:

```
ERR cleanup failed msg="close dagger session" err="shutdown: do shutdown: Post \"http://dagger/shutdown\": context deadline exceeded" duration=41.927581741s
Error: cleanup failed: "close dagger session": shutdown: do shutdown: Post "http://dagger/shutdown": context deadline exceeded
```

However, the engine logs indicate that the cache export succeeded:

```
time="2025-10-29T21:56:10Z" level=debug msg="finalized exporter" client_hostname=ip-192-168-129-205.ec2.internal client_id=ok6hevirad0rna055o310r3z8 session_id=4va5gib23c6dq54nb6xcf16jv spanID=aeaeb215ffcdec27 traceID=7e41954a60b711f98df1bcfe63d287c1
time="2025-10-29T21:56:10Z" level=debug msg="waited for cache export" client_hostname=ip-192-168-129-205.ec2.internal client_id=ok6hevirad0rna055o310r3z8 session_id=4va5gib23c6dq54nb6xcf16jv spanID=aeaeb215ffcdec27 traceID=7e41954a60b711f98df1bcfe63d287c1
time="2025-10-29T21:56:10Z" level=debug msg="done running cache export for client ok6hevirad0rna055o310r3z8" client_hostname=ip-192-168-129-205.ec2.internal client_id=ok6hevirad0rna055o310r3z8 session_id=4va5gib23c6dq54nb6xcf16jv spanID=aeaeb215ffcdec27 traceID=7e41954a60b711f98df1bcfe63d287c1
```

**Note**: I recently upgraded from 0.18.16, where this timeout did not occur and a long cache export did not cause a shutdown failure.

### Dagger version

dagger v0.19.3 (image://registry.dagger.io/engine:v0.19.3) linux/amd64

### Steps to reproduce

_No response_

### Log output

_No response_

### PR DESCRIPTION
**Pull request by idlsoft**
This should fix #11328, which can easily happen when a remote cache is defined

### CODE REVIEW

File: engine/client/client.go [hunk 1]
```diff
@@ -986,7 +986,15 @@ func (c *Client) shutdownServer() error {
 	// canceled
 	ctx := context.WithoutCancel(c.internalCtx)
 
-	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
+	timeout := 10 * time.Second
+	if timeoutStr, ok := os.LookupEnv("_EXPERIMENTAL_DAGGER_SHUTDOWN_TIMEOUT"); ok {
```
Comment (marcosnils) [inline engine/client/client.go]: nit: define this var as a constant as the other ones in the file.

**Review by marcosnils — APPROVED** [review]
LGTM left a small nit
