### PR TITLE
fix: don't trim all whitespace

### LINKED ISSUE #3990: 🐞 [Node SDK] `withExec` removes whitespace of arguments
### What is the issue?

When calling `withExec` and passing a single argument that contains whitespace, all whitespace is stripped.

For example, `.withExec(['echo', 'foo bar'])` will print `foobar`.

The expected output is `foo bar`.

### Log output

N/A

### Steps to reproduce

1. Run the following

```ts
import Client, { connect } from "@dagger.io/dagger";

connect(async (client: Client) => {
    await client.container().from('alpine:latest')
        .withExec(['echo', 'foo bar'])
}, { LogOutput: process.stdout })
```

2. observe that the output is `foobar` rather than the expected output

### Dagger version

dagger v0.2.36 (ea275a3ba) darwin/arm64

### OS version

macOS 12.1

### PR DESCRIPTION
**Pull request by rawkode**
When users pass strings for `client.directory().withNewFile()` or even to `container.withExec()`, this is removing all whitespace and breaking entrypoints, commands, and scripts.

fixes #3990

### CODE REVIEW

File: sdk/nodejs/api/utils.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ export function queryBuilder(q: QueryTree[]) {
   })
   query += "}"
 
-  return query.replace(/\s+/g, "")
+  return query;
```
Comment (phroggyy) [inline sdk/nodejs/api/utils.ts:38]:
```suggestion
  return query.trim();
```

We probably still want whitespace trimmed at the start and end of args, maybe?

**Comment by rawkode** [comment]
Ahh. I think it’s supposed to trim new lines?

**Comment by vito** [comment]
Great catch, thanks for the PR!

The tests are failing because it seems like this reformatting was done to prevent test comparisons from failing just because of whitespace. (Not sure.)

I'm not familiar with the JS stack, but maybe we could use a GraphQL parser/formatter to clean it up instead. Or maybe just apply the whitespace cleanup to both sides before doing the comparison in the tests.

If you don't have time to figure that out, I'm sure someone will get around to it Monday. :smile:

**Comment by marcosnils** [comment]
cc @slumbering since he probably has more context on the query builder.

**Comment by rawkode** [comment]
No problem. Thanks for picking this up quickly, it was blocking me :)

**Comment by slumbering** [comment]
Every lights are green @rawkode . I've replaced the `trim` method with the `.replace()` to remove every extra spaces and tests have been adapted

File: sdk/nodejs/api/utils.ts [hunk 2]
```diff
@@ -35,7 +35,7 @@ export function queryBuilder(q: QueryTree[]) {
   })
   query += "}"
 
-  return query.replace(/\s+/g, "")
+  return query.replace(/\s+/g, " ")
```
Comment (vito) [inline sdk/nodejs/api/utils.ts:38]: I think we still don't want this since it'll mess up the semantics of the query, not just the syntax. For example if someone tries to do this:

```
echo "foo    bar"
```

it'll get replaced with this:

```
echo "foo bar"
```

**Comment by slumbering** [comment]
Pushing a fix now

File: sdk/nodejs/api/utils.ts (hunk 2 above)
Comment (slumbering) [reply sdk/nodejs/api/utils.ts]: Just pushed a fix that return a raw query. 
Queries are only sanitize for tests

**Review by slumbering — APPROVED** [review]
Ready to be merged
