### PR TITLE
Apply Dagger engine config defaults at runtime, configure MTU that matches default interface

### LINKED ISSUE #4652: 🐞 network issue with engine@v0.3.13 in k8s pod
### What is the issue?

May cause by https://github.com/dagger/dagger/pull/4505

Here a new search in `/etc/resolv.conf` added before k8s searches

```conf
search dns.dagger
search gitlab.svc.cluster.local. svc.cluster.local. cluster.local. openstacklocal
options ndots:5
```

Then network because very slow to fetch anything.

### Log output

_No response_

### Steps to reproduce

_No response_

### SDK version

Go SDK v0.4.6

### OS version

Unbuntu

### PR DESCRIPTION
**Pull request by vito**
* Follow-up to #4657
* Fixes #4652

Now we handle Buildkit config defaults in `cmd/engine/` on start. We'll load the user-provided config, apply our defaults on top, and then apply the Buildkit defaults.

It also detects the MTU of the default interface and sets the same value in the `bridge` plugin, which should fix #4652

### CODE REVIEW

File: cmd/engine/config.go [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+		cfg.CNIConfigPath = cniConfigPath
+	}
+	if cfg.CNIPoolSize == 0 {
+		cfg.CNIPoolSize = 16
+	}
+}
+
+func cniConfig(name, subnet string) ([]byte, error) {
+	ip, err := gateway.DiscoverInterface()
+	if err != nil {
```
Comment (sipsma) [inline cmd/engine/config.go:77]: extreme nit: it's technically valid to not have a default gateway (e.g. you have disabled internet access), so maybe just default to 1500 and print a warning log if this goes wrong? If there's any complication around that though then doesn't matter, most likely an obscure case (I think?)

**Review by sipsma — APPROVED** [review]

File: cmd/engine/config.go (hunk 1 above)
Comment (vito) [reply cmd/engine/config.go]: Done!
