### PR TITLE
fix(cli): fix terminal on windows

### LINKED ISSUE #9096: 🐞 terminal fails on Dagger windows distribution
### What is the issue?

It's been a long while since I have used the `terminal` feature, but I know it did work for sure around the v0.10. There's a chance a bug was introduced a while back and I can't give a good timeline of when something may have changed, sorry.

The `terminal` feature is not working on the windows binary and I think it's easy to replicate with just a simple container from and terminal chained command.

I noticed something odd, after trying to debug some adhoc stuff I was learning with C++ build environments in docker, so i thought i'd use Dagger for this. I came across this error and thought maybe it's the docker image I was using, tried a few things, got it working in WSL but now I realised i think the problem is more general and not specific to an image, example below is the basic ubuntu image and that doesn't seem to work.

### Dagger version

dagger v0.14.0 (registry.dagger.io/engine:v0.14.0) windows/amd64

### Steps to reproduce

```
dagger core container from --address ubuntu terminal
```

Swap the image with anything, alpine etc and I'm confident the same result with occur, you are not able to get into a terminal from the dagger windows client binary

### Log output

```
dagger core container from --address ubuntu terminal                            PS  12:30:12 
✔ connect 0.2s
✔ inspecting core types 0.2s
✔ parsing command line arguments 0.0s
✔ container: Container! 0.0s
✔ Container.from(address: "ubuntu"): Container! 0.4s
✘ Container.terminal: Container! 0.7s
! failed to forward exit code: failed to close terminal: EOF
┃ dagger / $
  ✔ start sh 0.7s

Full trace at https://dagger.cloud/mageep/traces/4756d309d0c41f6979d25cff3a6f02eb

Error: response from query: input: container.from.terminal resolve: failed to forward exit code: failed to close terminal: EOF               
Run 'dagger core container from terminal --help' for usage.
```

Trying on my WSL, with the exact same command, it worked.

```
mageep@PATRICK-PC:~$ dagger version
dagger v0.14.0 (registry.dagger.io/engine:v0.14.0) linux/amd64
mageep@PATRICK-PC:~$ dagger core container from --address ubuntu terminal
● Attaching terminal:
    container: Container!
    Container.from(address: "docker.io/library/ubuntu:latest@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab"): Container!

dagger / $
```

### PR DESCRIPTION
**Pull request by rajatjindal**
Fixes #9096

### CODE REVIEW

File: dagql/idtui/frontend_pretty.go [hunk 1]
```diff
@@ -742,7 +742,7 @@ func (fe *frontendPretty) update(msg tea.Msg) (*frontendPretty, tea.Cmd) { //nol
 			cmd = &wrapCommand{
 				ExecCommand: cmd,
 				before: func() error {
-					ttyFd := int(os.Stdout.Fd())
+					ttyFd := int(os.Stdin.Fd())
```
Comment (jedevc) [inline dagql/idtui/frontend_pretty.go:745]: Hm, just to throw an edge-case your way - this should *also* work if `os.Stdin` is not really a tty. e.g. on linux this is like `echo "" | dagger core container from --address=alpine terminal`. Note, how this works - since stdin isn't a TTY, we try and open `/dev/tty` instead.

To handle this, we should use the same logic as we do with `findTTY`s https://github.com/dagger/dagger/blob/c91fe3d76dc580d662215f654b371b756f48bd1d/dagql/idtui/frontend_pretty.go#L206-L216 - perhaps we can save the result that we pass to `tea.WithInput` onto `frontendPretty` somewhere, and then use that instead?

**Comment by rajatjindal** [comment]
Hi @jedevc 

do you have a specific scenario in mind where a user would do something like this?

File: dagql/idtui/frontend_pretty.go (hunk 1 above)
Comment (rajatjindal) [reply dagql/idtui/frontend_pretty.go:745]: Hi @jedevc

do you have a specific scenario in mind where a user would do something like this?

Comment (jedevc) [reply dagql/idtui/frontend_pretty.go:745]: Yeah, it's more applicable when using `dagger shell`:

```
$ echo ".core | container | from alpine | terminal" | dagger shell
```

Then we have to spawn a `terminal`, but the stdin is actually just a pipe from `echo`.

Comment (rajatjindal) [reply dagql/idtui/frontend_pretty.go]: thank you Justin. 👍

I have pushed the code as suggested and also tested with Mac/Windows client.

thanks

File: dagql/idtui/frontend_pretty.go [hunk 2]
```diff
@@ -742,7 +742,24 @@ func (fe *frontendPretty) update(msg tea.Msg) (*frontendPretty, tea.Cmd) { //nol
...
 				before: func() error {
-					ttyFd := int(os.Stdout.Fd())
+					var in *os.File
+					inr, _ := findTTYs()
+					if inr != nil {
+						in = inr.(*os.File)
+					}
+
+					if in == nil {
+						tty, err := openInputTTY()
```
Comment (jedevc) [inline dagql/idtui/frontend_pretty.go:752]: We should avoid opening this again - it should already be open right? 

> Perhaps we can save the result that we pass to `tea.WithInput` onto `frontendPretty` somewhere, and then use that instead?

I think we can save it from the `runWithTUI` function - or is there some reason that we need to find all the TTYs again?

Comment (rajatjindal) [reply dagql/idtui/frontend_pretty.go:752]: no, this is most likely my bad. I'll take a look again at this.

Comment (rajatjindal) [reply dagql/idtui/frontend_pretty.go]: I made changes to store the already opened handle in `frontendPretty` struct. I tested with Mac client, it works fine. i will test it with Windows client once as well and report back here.

I also want to look at it with fresh eyes to ensure there is no other optimization we could do for these changes.

**Comment by rajatjindal** [comment]
I made some more changes today to fix CI failures, so I want to test this once again with a windows client machine. I will report back the results by tomorrow.

**Review by jedevc — APPROVED** [review]

**Comment by jedevc** [comment]
@rajatjindal is this good to go?

**Comment by rajatjindal** [comment]
> @rajatjindal is this good to go?

give me few mins to verify with my windows laptop. I'll do it right away.

**Comment by rajatjindal** [comment]
> > @rajatjindal is this good to go?
> 
> give me few mins to verify with my windows laptop. I'll do it right away.

I can confirm that this works with windows as well as darwin client now. 👍 🎉

**Comment by jedevc** [comment]
Pushed a changelog - will merge when CI passes :tada:
