### PR TITLE
engine: return error if services don't have a command set

### LINKED ISSUE #9190: 🐞 existing services break in 0.15
### What is the issue?

I have a sample go application (https://github.com/levlaz/snippetbox) that installs mariadb (https://daggerverse.dev/mod/github.com/levlaz/daggerverse/mariadb@cea1668da940b45864116049bd20087855c8c787) from the daggerverse and mounts it as a service binding. 

THe mariadb module is targeting 0.11.6 and the snippetbox module is targeting   0.13.16

This is no longer working in 0.15 with the following error: 

```
│ ✔ .withEnvVariable(name: "CACHEBUSTER", value: "2024-12-12 22:56:27.108879878 +0000 UTC m=+0.053134793"): Container! 0.0s
│ ✘ .withExec(args: ["sh", "-c", "mysql -h db -u root < internal/db/init.sql"]): Container! 0.1s
│ ┃ mysql: Deprecated program name. It will be removed in a future release, use '
│ ┃ /bin/mariadb' instead                                                        
│ ┃ ERROR 2026 (HY000): TLS/SSL error: self-signed certificate                   
│ ! process "sh -c mysql -h db -u root < internal/db/init.sql" did not complete successfully: exit code: 1
│ ○ .withExec(args: ["sh", "-c", "mysql -h db -u root snippetbox < internal/db/seed.sql"]): Container! 0.0s
│ ○ .withExec(args: ["go", "run", "./cmd/web", "--dsn", "web:pass@tcp(db)/snippetbox?parseTime=true"]): Container! 0.0s
✘ .terminal: Container! 4.9s
! failed to start service: solve mount /: process "sh -c mysql -h db -u root < internal/db/init.sql" did not complete successfully: exit code: 1
```

I suspect its not able to get the service to work due to the new API change, but I was under the impression that this change should not break existing pipelines like this. 

### Dagger version

dagger v0.15.0 (registry.dagger.io/engine:v0.15.0) darwin/arm64

### Steps to reproduce

dagger -m github.com/levlaz/snippetbox call server

### Log output

Here's a trace: https://dagger.cloud/levs-test-org/traces/f06d326bb79ffd99fb7afdc647b58f21

### PR DESCRIPTION
**Pull request by marcosnils**
this addresses the issue introduced in v0.15.0 where services will hang
to start if neither CMD or ENTRYPOINT is used.

fixes #9190

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

**Comment by marcosnils** [comment]
moving to draft per last @jpadams 's comment here: https://discord.com/channels/707636530424053791/1318184687914713148/1319028692676251678

File: core/schema/container.go [hunk 1]
```diff
@@ -1011,7 +1011,9 @@ type containerWithDefaultArgs struct {
 }
 
 func (s *containerSchema) withDefaultArgs(ctx context.Context, parent *core.Container, args containerWithDefaultArgs) (*core.Container, error) {
-	return parent.UpdateImageConfig(ctx, func(cfg specs.ImageConfig) specs.ImageConfig {
+	c := parent.Clone()
+	c.DefaultArgs = args.Args
```
Comment (jedevc) [inline core/schema/container.go:1015]: Ok, I see.

Because `DefaultArgs` is only ever set to the same as `Cmd`, probably doesn't make sense to track it as a slice. Maybe we can just track `DefaultArgs bool` for explicitly tracking this error.

File: core/integration/git_test.go [hunk 2]
```diff
@@ -438,6 +438,7 @@ func (GitSuite) TestServiceStableDigest(ctx context.Context, t *testctx.T) {
 			WithMountedDirectory("/repo", c.Git(url, dagger.GitOpts{
 				ExperimentalServiceHost: svc,
 			}).Branch("main").Tree()).
+			WithDefaultArgs([]string{"/bin/sh"}).
```
Comment (jedevc) [inline core/integration/git_test.go:441]: nit: this command isn't a service - we should explicitly make it a command like `sleep` or something, instead of one that would just immediately exit if it was started.

(nit because the service isn't really started, so it doesn't matter)

File: core/container.go [hunk 3]
```diff
@@ -1710,14 +1710,26 @@ func (container *Container) AsServiceLegacy(ctx context.Context) (*Service, erro
...
+	if len(args.Args) == 0 &&
+		len(container.Config.Cmd) == 0 &&
+		len(container.Config.Entrypoint) == 0 {
+		return nil, ErrNoSvcCommand
+	}
+
+	useEntrypoint := args.UseEntrypoint
+	if len(container.Config.Entrypoint) > 0 {
+		useEntrypoint = true
+	}
```
Comment (jedevc) [inline core/container.go:1722]: Hm, if `withDefaultArgs` is called before this, this will now apply the default entrypoint?

Seems like a mismatch with the proposal in https://github.com/dagger/dagger/issues/9305#issue-2766581758.

Comment (marcosnils) [reply core/container.go:1722]: Yes, TBH I'm a bit confused about how this logic should actually work. Imagine the following scenario: 

```
myApiContainer := dag.Container().From("blah").WithEntrypoint("ept").WithDefaultArgs("blah") // this is my app container that the pipeline builds which later I want to publish to my OCI registry

//  as part of myApiContainer tests somewhere else in the code I do: 

svc := myApiContainer.AsService()

dag.Container().WithServiceBinding("api",svc)......
```

^ in this case, if we apply the logic to disable the entrypoint when setting `WithDefaultArgs` the above scenario ends up being super confusing since if you `pull` the container from the OCI registry it works, but if I use the one you've built it doesn't. :grimacing:

Comment (jedevc) [reply core/container.go]: Sigh - this is annoying, and I don't think is possible to fully resolve perfectly. That said, it's fairly minor? so happy to defer until someone hits it, maybe some of the other refactors we make to the service API in the future will help resolve this.

---

As a *potential* alternative - we could have this exact case be an error case (literally just changing `useEntrypoint = true` to `return fmt.Errorf("cannot execute base image default args without entrypoint")` - trying to execute the base image's `CMD` without it's `ENTRYPOINT` is invalid, so we could error (this would force users to put the `UseEntrypoint` in there).

This minimizes the inconsistent behavior from pushing and re-pulling - it makes the error show again even if `WithDefaultArgs` was used when pushed, but I think this is actually *probably* what we would expect.

But also this doesn't actually accomplish the out-of-the-box compatibility from https://github.com/dagger/dagger/issues/9305 - but it does steer users towards easier upgrades by having *clear explicit errors*.

File: core/container.go [hunk 4]
```diff
@@ -1710,14 +1713,26 @@ func (container *Container) AsServiceLegacy(ctx context.Context) (*Service, erro
...
+	if len(args.Args) == 0 &&
+		len(container.Config.Cmd) == 0 &&
+		len(container.Config.Entrypoint) == 0 {
+		return nil, ErrNoSvcCommand
+	}
+
+	useEntrypoint := args.UseEntrypoint
+	if len(container.Config.Entrypoint) > 0 && !container.DefaultArgs {
+		useEntrypoint = true
+	}
```
Comment (jedevc) [inline core/container.go:1725]: Yup, can confirm this implements the proposal in https://github.com/dagger/dagger/issues/9305 as desired. LGTM :tada:

**Review by jedevc — COMMENTED** [review]
Yup, can confirm this implements the proposal in https://github.com/dagger/dagger/issues/9305 as desired. LGTM :tada:

Holding off an approval though until we can confirm that we're happy to compromise here: https://github.com/dagger/dagger/pull/9247#discussion_r1907264949

**Review by jpadams — APPROVED** [review]
LGTM 🙏 

Tested manully here: https://discord.com/channels/707636530424053791/1318184687914713148/1327416811309760572
