### PR TITLE
Convert home relative paths for cache options

### LINKED ISSUE #2003: 🐞 ~ is not expanded in --cache-to and --cache-from switches
### What is the issue?

I run this:
```console
dagger do build --cache-from type=local,src=~/cc --cache-to type=local,mode=max,dest=~/cc
```
and in current directory new folder was create that was named `~`.

dagger should expand ~ to current user home folder path.

### Log output

nothing in logs

### Steps to reproduce
```console
dagger do build --cache-from type=local,src=~/cc --cache-to type=local,mode=max,dest=~/cc
```
### Dagger version

0.2.4

### OS version

ubuntu 21.10

### PR DESCRIPTION
**Pull request by Liberatys**
Signed-off-by: Nick Flückiger <nick.flueckiger@renuo.ch>

This pr converts the src/dest in cache options from home relative paths e.g. ~/path to absolute paths.

Example:

`./cmd/dagger/dagger do build --cache-from type=local,src=~/cc `

is being interpreted as 

./cmd/dagger/dagger do build --cache-from type=local,src=/Users/liberatys/cc (/Users/liberatys being my home-dir)

Fixes #2003

### CODE REVIEW

File: cmd/dagger/cmd/common/common.go [hunk 1]
```diff
@@ -82,6 +84,23 @@ func ValueDocOneLine(val *compiler.Value) string {
...
+func convertRelativePaths(cacheOptionEntries []buildkit.CacheOptionsEntry) []buildkit.CacheOptionsEntry {
+    var convertedOptions = cacheOptionEntries
+    var pathableAttributes []string = []string{ "src", "dest" }
+
+    dirname, _ := os.UserHomeDir()
+
+    for _, option := range convertedOptions {
+        for _, key := range pathableAttributes {
+            if _, ok := option.Attrs[key]; ok {
+                option.Attrs[key] = strings.Replace(option.Attrs[key], "~", dirname, -1)
```
Comment (helderco) [inline cmd/dagger/cmd/common/common.go:96]: We use https://github.com/mitchellh/go-homedir for this. You can look for examples by searching for `homedir.Expand`.

**Review by helderco — CHANGES_REQUESTED** [review]

**Review by helderco — APPROVED** [review]

**Comment by helderco** [comment]
Thanks @Liberatys, please squash your commits and fix the DCO check: [Contributing guidelines](https://github.com/dagger/.github/blob/7acc6f1929dc9f5365908fc970eed2fece70476e/CONTRIBUTING.md)

**Review by helderco — CHANGES_REQUESTED** [review]
Thanks @Liberatys, please squash your commits and fix the checks: [Contributing guidelines](https://github.com/dagger/.github/blob/main/CONTRIBUTING.md)

**Comment by gerhard** [comment]
This looks good to me.

You have a fair amount of experience with this @TomChv, how does this change fit with what you have been working on in this area?

**Review by helderco — APPROVED** [review]

File: cmd/dagger/cmd/common/common.go [hunk 2]
```diff
@@ -82,6 +84,21 @@ func ValueDocOneLine(val *compiler.Value) string {
 	return strings.Join(docs, " ")
 }
 
+func convertRelativePaths(cacheOptionEntries []buildkit.CacheOptionsEntry) []buildkit.CacheOptionsEntry {
+	var convertedOptions = cacheOptionEntries
```
Comment (aluzzardi) [inline cmd/dagger/cmd/common/common.go:88]: If this variable necessary?

File: cmd/dagger/cmd/common/common.go [hunk 3]
```diff
@@ -82,6 +84,21 @@ func ValueDocOneLine(val *compiler.Value) string {
...
+	var pathableAttributes = []string{"src", "dest"}
```
Comment (aluzzardi) [inline cmd/dagger/cmd/common/common.go:89]: nit: `pathableAttributes := ...` instead of `var`

File: cmd/dagger/cmd/common/common.go [hunk 4]
```diff
@@ -82,6 +84,21 @@ func ValueDocOneLine(val *compiler.Value) string {
...
+
+	for _, option := range convertedOptions {
+		for _, key := range pathableAttributes {
+			if _, ok := option.Attrs[key]; ok {
+				option.Attrs[key], _ = homedir.Expand(option.Attrs[key])
```
Comment (aluzzardi) [inline cmd/dagger/cmd/common/common.go:94]: It's better not to ignore the error.

If you want to avoid returning an error to keep this function simple, I would add a `if err != nil { panic(err) }`

**Review by aluzzardi — COMMENTED** [review]
Looks good! Left a couple of minor comments

File: cmd/dagger/cmd/common/common.go (hunk 2 above)
Comment (Liberatys) [reply cmd/dagger/cmd/common/common.go]: No 👍🏻 Initially I was wondering if adding a copy/clone of the array would be beneficial. (To prevent mutation of passed params). But I guess here it doesn't really make a big difference. (This was a placeholder ^^).

File: cmd/dagger/cmd/common/common.go (hunk 3 above)
Comment (aluzzardi) [reply cmd/dagger/cmd/common/common.go:88]: Only comment remaining and then we're good to merge!

**Comment by helderco** [comment]
Needs a rebase.

**Comment by TomChv** [comment]
And prefix your commit with `chore:` or `feat:` so `CHANGELOG` will ignore those who are not relevant.
You can also clean up your commit history ;)

**Comment by Liberatys** [comment]
@slumbering hey there :D Hope the commit/pr is now to your satisfaction ^^
