### PR TITLE
fix: support kernels without legacy xtables (6.17+)

### LINKED ISSUE #11607: Dagger Engine fails on Linux kernel 6.17+ (Talos 1.12, RHEL 10) due to disabled legacy xtables
### What is the issue?

> [!NOTE]
> AI wrote this issue. I have proofread/verified correctness to the best of my ability.
>
> Dagger on Talos worked perfectly for me until 1.12.0

Dagger Engine fails to start on systems running Linux kernel 6.17+ where `CONFIG_NETFILTER_XTABLES_LEGACY` is disabled.

### Error Message

```
dagger-engine: failed to create engine: failed to create network providers: CNI setup error:
plugin type="bridge" failed (add): failed to list chains: running [/usr/sbin/iptables -t nat -S --wait]:
exit status 3: iptables v1.8.11 (legacy): can't initialize iptables table `nat': Table does not exist
(do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

### Environment

- **Dagger version:** 0.19.8
- **Platform:** Kubernetes (Talos Linux 1.12.0)
- **Kernel:** 6.18.1-talos
- **Helm chart:** dagger-helm 0.19.8

#### 1. Dagger explicitly uses iptables-legacy

In [PR #7670](https://github.com/dagger/dagger/pull/7670) (June 2024), Dagger reverted to iptables-legacy:

> "the v0.11.7 release bumped the base images that the engine uses which caused a newer version of iptables to be used. **This newer version of iptables which uses nftables is still not widely supported** and it's currently causing issues for some users."

The fix installed both `iptables` and `iptables-legacy` packages to force legacy mode.

#### 2. Linux kernel 6.17+ disables legacy xtables by default

Starting with kernel 6.17, `CONFIG_NETFILTER_XTABLES_LEGACY` defaults to `n` (disabled).

**Evidence from [LWN](https://lwn.net/Articles/1040082/):**
> "CONFIG_NETFILTER_XTABLES_LEGACY defaulted to 'n'" during kernel upgrades from 6.16 to 6.17.

**Evidence from [Void Linux #57399](https://github.com/void-linux/void-packages/issues/57399):**
Users reported after upgrading to kernel 6.17.0:
```
modprobe: FATAL: Module ip_tables not found in directory /lib/modules/6.17.0_1
```

#### 3. Talos 1.12.0 uses kernel 6.18.1 with legacy xtables disabled

**From [Talos 1.12.0 release notes](https://github.com/siderolabs/talos/releases/tag/v1.12.0):**
> "Linux: 6.18.1"

**From [Talos kernel config](https://github.com/siderolabs/pkgs/blob/main/kernel/build/config-amd64):**
```
# CONFIG_NETFILTER_XTABLES_LEGACY is not set
```

This confirms the kernel is compiled without legacy xtables support.

### Affected Platforms

| Platform | Kernel | Legacy xtables | Status |
|----------|--------|----------------|--------|
| Talos Linux 1.11.x | ~6.6.x | Enabled | ✅ Works |
| Talos Linux 1.12.0 | 6.18.1 | **Disabled** | ❌ Broken |
| Void Linux 6.17+ | 6.17+ | Disabled by default | ❌ Broken |
| Arch Linux 6.17+ | 6.17+ | Disabled by default | ❌ Broken |
| RHEL 10 (upcoming) | 6.x+ | Expected disabled | ⚠️ At risk |

#### Option 1: Support nftables backend

The CNI bridge plugin already supports nftables via the `ipMasqBackend` option.

**From [CNI bridge plugin docs](https://www.cni.dev/plugins/current/main/bridge/):**
> `ipMasqBackend` (string, optional): IP masquerading implementation to use when ipMasq is true. Can be **"iptables" or "nftables"**. Defaults to "iptables", unless only "nftables" is available.

Dagger could:
1. Configure CNI to use `ipMasqBackend: nftables`
2. Use `iptables-nft` instead of `iptables-legacy` in container images
3. Auto-detect available backend at runtime

#### Option 2: Detect and fail gracefully

If legacy xtables is required, detect its absence at startup and provide a clear error message explaining the kernel requirement.

### Reproduction Steps

1. Deploy Dagger Engine on Talos Linux 1.12.0:
   ```bash
   helm upgrade --install --namespace=dagger --create-namespace \
       dagger oci://registry.dagger.io/dagger-helm
   ```
2. Engine pod enters CrashLoopBackOff
3. Check logs: `kubectl logs -n dagger dagger-dagger-helm-engine-0`
4. Observe the iptables NAT table error

### Workarounds

Currently, the only workarounds are:
- **Downgrade kernel** to one with `CONFIG_NETFILTER_XTABLES_LEGACY=y`
- **Request OS vendor** to enable legacy xtables (not ideal long-term)

### Why This Matters

This will become increasingly common as distributions adopt kernel 6.17+ defaults:

1. **Kernel direction is clear** - Legacy xtables is being phased out in favor of nftables
2. **Enterprise impact** - RHEL 10 and derivatives will likely follow this default
3. **Cloud-native environments** - Talos, Flatcar, and other immutable OSes track upstream defaults

### References

| Link | Evidence |
|------|----------|
| [Dagger PR #7670](https://github.com/dagger/dagger/pull/7670) | Dagger reverted to iptables-legacy |
| [Talos 1.12.0 Release](https://github.com/siderolabs/talos/releases/tag/v1.12.0) | Kernel 6.18.1 |
| [Talos kernel config](https://github.com/siderolabs/pkgs/blob/main/kernel/build/config-amd64) | `CONFIG_NETFILTER_XTABLES_LEGACY is not set` |
| [Void Linux #57399](https://github.com/void-linux/void-packages/issues/57399) | Kernel 6.17 broke iptables-legacy |
| [LWN Article](https://lwn.net/Articles/1040082/) | CONFIG_NETFILTER_XTABLES_LEGACY defaults to n |
| [CNI Bridge Plugin Docs](https://www.cni.dev/plugins/current/main/bridge/) | `ipMasqBackend` supports nftables |

### PR DESCRIPTION
**Pull request by shepherdjerred**
## Summary
Fix Dagger Engine failing on Linux kernel 6.17+ where `CONFIG_NETFILTER_XTABLES_LEGACY` is disabled.

Image available here: https://github.com/users/shepherdjerred/packages/container/package/dagger-engine

```
2025-12-29T23:34:37.727Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.727Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.732Z | time="2025-12-29T23:34:37Z" level=info msg="auto snapshotter: using overlayfs"
2025-12-29T23:34:37.735Z | time="2025-12-29T23:34:37Z" level=warning msg="failed to release network namespace \"kxhj354vbn6ent9a2x1tp6s9d\" left over from previous run: plugin type=\"loopback\" failed (delete): unknown FS magic on \"/var/lib/dagger/net/cni/kxhj354vbn6ent9a2x1tp6s9d\": 2fc12fc1"
2025-12-29T23:34:37.767Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.767Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.794Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.794Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.824Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.824Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.852Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.852Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.878Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.878Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.905Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.905Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.931Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.931Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.959Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.959Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:37.988Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:37.988Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:38.017Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:38.017Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
2025-12-29T23:34:38.073Z | dnsmasq[739]: read /etc/hosts - 18 names
2025-12-29T23:34:38.073Z | dnsmasq[739]: read /var/run/containers/cni/dnsname/dagger/addnhosts - 0 names
```

```
Run ARGS=(
1   : connect
1   : [0.0s] | cloud url=https://dagger.cloud/traces/setup
2   : ┆ starting engine
2   : ┆ starting engine DONE [0.0s]
3   : ┆ connecting to engine
3   : ┆ [0.1s] | 23:48:59 INF connected name=dagger-dagger-helm-engine-0 client-version=v0.19.8 server-version=v0.19.8
3   : ┆ connecting to engine DONE [0.1s]
4   : ┆ starting session
4   : ┆ starting session DONE [0.1s]
1   : connect DONE [0.3s]
5   : load module: .
6   : ┆ finding module configuration
7   : ┆ initializing module
6   : ┆ finding module configuration DONE [13.1s]
```

Tested on Talos Linux 1.12.0

Fixes #11607

## Changes
1. Switch from `iptables` to `iptables-nft` package in Wolfi base image (uses nftables kernel API)
2. Add runtime detection for legacy xtables availability
3. Configure CNI bridge plugin to use `nftables` backend when legacy unavailable

### Background
Starting with Linux kernel 6.17, `CONFIG_NETFILTER_XTABLES_LEGACY` defaults to disabled, removing the legacy `ip_tables` kernel modules. This affects:
- Talos Linux 1.12+ (kernel 6.18.1)
- RHEL 10 (upcoming)
- Arch Linux with kernel 6.17+
- Void Linux with kernel 6.17+

### Solution
**Package Change (`toolchains/engine-dev/build/builder.go`):**
- Switch to `iptables-nft` and `ip6tables-nft` packages
- These use the nftables kernel API (available since kernel 3.13)
- The go-iptables library auto-detects nft mode from `iptables -V` output
- Ensures CNI firewall plugin works on both old and new kernels

**Runtime Detection (`internal/buildkit/util/network/cniprovider/bridge.go`):**
- New `detectIPMasqBackend()` function checks:
  1. `/proc/net/ip_tables_names` existence (legacy xtables indicator)
  2. Probes `iptables -t nat -L` for "Table does not exist" error
- If legacy xtables unavailable, configures CNI bridge with `ipMasqBackend: "nftables"`
- Debug-level logging when falling back to nftables

## Testing
- ✅ Code compiles and passes `go vet`
- ⏳ Manual testing needed on Talos 1.12 (kernel 6.18.1)
- ⏳ Regression testing needed on Docker Desktop / standard kernels

## Related
- Previous work: #7670 (reverted to iptables-legacy for different issue)
- CNI bridge plugin docs: https://www.cni.dev/plugins/current/main/bridge/

### CODE REVIEW

File: toolchains/engine-dev/build/builder.go [hunk 1]
```diff
@@ -111,8 +111,8 @@ func (build *Builder) Engine(ctx context.Context) (*dagger.Container, error) {
 		"git", "openssh-client",
 		// for decompression
 		"pigz", "xz",
-		// for CNI
-		"iptables", "ip6tables", "dnsmasq",
+		// for CNI (use nft variants for compatibility with kernels lacking legacy xtables)
+		"iptables-nft", "dnsmasq",
```
Comment (marcosnils) [inline toolchains/engine-dev/build/builder.go:115]: does this work for legacy  xtables also?

Comment (shepherdjerred) [reply toolchains/engine-dev/build/builder.go:115]: My understanding is that this will work for both xtables and nftables. with that said I am not an expert.

https://github.com/wolfi-dev/os/blob/main/iptables.yaml#L275-L277

https://github.com/wolfi-dev/os/pull/76286

> Ideally everything should be able to just use iptables-nft; packages that require iptables-legacy are depending on ancient kernel features and may need special handling.

Comment (marcosnils) [reply toolchains/engine-dev/build/builder.go:115]: awesome, that must be it then! the fact that tests passed also indicates that we're good with the xtables compat.

**Review by marcosnils — APPROVED** [review]

**Comment by marcosnils** [comment]
@shepherdjerred small nit about the DCO check please :pray:

**Comment by shepherdjerred** [comment]
I believe I've fixed the DCO check. Thanks for the review!

**Comment by ReillyBrogan** [comment]
I hit this same issue on AerynOS, though in my case as I am one of the distro maintainers I was just able to re-enable legacy xtables in the kernel. Beyond just making sure that dagger works with newer kernels it's important to resolve this because running a system with both iptables and nftables rules is technically not a supported configuration and the fact that it hasn't been a major issue is likely more to do with the fact that devices running dagger are usually only running dagger and not mixed workloads.

I'd note that the Kubernetes project went through this several years ago and it would be wise to take a look at how they resolved it:
- https://github.com/kubernetes/kubernetes/issues/71305
- https://github.com/kubernetes/kubernetes/pull/82966

**Comment by ReillyBrogan** [comment]
I found the latest implementation that k8s uses [here](https://github.com/kubernetes-sigs/iptables-wrappers/tree/master)

**Comment by ezynda3** [comment]
Waiting for this to get merged as I haven't been able to play with dagger for several months on my NixOS machine...

**Review by sipsma — CHANGES_REQUESTED** [review]
Several of the test runs succeeded but were suspiciously slow (20m vs. less than 10m previously), so I'd like to take a look at this a little bit more before merging to make sure it doesn't cause a perf regression for some reason.

**Comment by sipsma** [comment]
Ended up needing to revert this before the release, we should revisit it though https://github.com/dagger/dagger/pull/11692
