### PR TITLE
experimental `do --dry-run` mode

### LINKED ISSUE #2299: `--help` suppressed plan loading errors
```console
$ dagger do -p ./plan/do/do_flags.cue test --help
Usage: 
  dagger do [flags]
```

vs

```console
$ dagger do -p ./plan/do/do_flags.cue test
failed to load plan: "actions.test.message" is not set:
    ./plan/do/do_flags.cue:21:3
    ./plan/do/do_flags.cue:25:4


Usage: 
  dagger do [flags]
```

### PR DESCRIPTION
**Pull request by aluzzardi**
Fixes https://github.com/dagger/dagger/issues/2299

Related to https://github.com/dagger/dagger/issues/2331

This adds an experimental `--dry-run` **experimental** flag to `dagger do` that doesn't actually execute tasks. Can be used to validate the plan.

```console
$ dagger do build --experimental --dry-run
[✔] client.filesystem.".".read
[✔] actions.build.go.container
[✔] actions.version
[✔] client.platform
[✔] client.filesystem."./".read
[✔] actions.build.docker
[✔] actions.build.go.container.export
[✔] client.filesystem."./bin".write
```

### CODE REVIEW

File: cmd/dagger/cmd/do.go [hunk 1]
```diff
@@ -59,7 +59,7 @@ var doCmd = &cobra.Command{
 		daggerPlan, err := loadPlan(viper.GetString("plan"))
 		if err != nil {
 			if viper.GetBool("help") {
-				doHelpCmd(cmd, nil, nil, nil, targetPath, nil)
+				doHelpCmd(cmd, nil, nil, nil, targetPath, []string{err.Error()})
 				os.Exit(0)
```
Comment (aluzzardi) [inline cmd/dagger/cmd/do.go:63]: @jlongtine Is it actually alright if we `Exit(0)` even if the plan has problems?

I'm realizing now the logic was on purpose: if `--help` is provided, suppress plan errors, exit 0.

Comment (marcosnils) [reply cmd/dagger/cmd/do.go:63]: Traditionally CLI's don't perform any action if `--help` is provided  even though commands or other flags are specified and they usually return with exit code == 0. They current behavior is what I'd expect naturally when interacting with the CLI.

Having said that, if we want to still validate the plan and return something !=0, I think we should make explicit what the expected behavior is.

Comment (jlongtine) [reply cmd/dagger/cmd/do.go:63]: Hmm... Yeah, that's an interesting case. I think you're correct about why I did it, but I'm not sure what the "right" way to do it would be in this case.

Comment (jlongtine) [reply cmd/dagger/cmd/do.go:63]: I think my personal preference would be to print errors + exit(0) because they're using the `--help` flag.

**Comment by aluzzardi** [comment]
@marcosnils Agree with your feedback.

Attempted this instead: leaving `--help` untouched, I added a `--dry-run` flag (behind the `--experimental` flag).

It does everything `dagger do` does, except tasks are not actually executed (but they do show up in logs).

It's similar to the `dagger verify` command you were proposing but I figured it's easier to add an experimental flag and tweak it later rather than a command.

/cc @jpadams @shykes

**Review by shykes — APPROVED** [review]
Looks useful & low risk with the experimental flag.

Note: separately from this it would still be useful to get a warning that something went wrong in `—help`

File: plan/runner.go [hunk 2]
```diff
@@ -156,6 +158,11 @@ func (r *Runner) taskFunc(flowVal cue.Value) (cueflow.Runner, error) {
 			lg.Debug().Str("dependency", dep.Path().String()).Msg("dependency detected")
 		}
 
+		if r.dryRun {
+			lg.Info().Dur("duration", 0).Str("state", task.StateCompleted.String()).Msg(task.StateCompleted.String())
```
Comment (marcosnils) [inline plan/runner.go:162]: Shall we add  a new state so we can show the output in a different color (blue maybe?) for dry run actions?

**Comment by marcosnils** [comment]
LGTM @aluzzardi. I guess this can close #2331  until we find a more solid use-case to bring it back

**Review by marcosnils — APPROVED** [review]

**Review by TomChv — APPROVED** [review]
LGTM

**Comment by aluzzardi** [comment]
> Shall we add a new state (DryRun?) so we can show the output in a different color (cyan maybe?) for dry run actions?

Added a `Skipped` state, WDYT?

> I guess this can close https://github.com/dagger/dagger/issues/2331 momentarily until we find a more solid use-case to bring it back

I think this only partially fixes #2331, I do think we still need a `verify`-like command. Your call as to whether close and re-open later or leave it open

**Comment by marcosnils** [comment]
> I think this only partially fixes #2331, I do think we still need a `verify`-like command. Your call as to whether close and re-open later or leave it open

just to make sure we're in the same page. Will `dagger verify` do anything differently initially from what `--dry-run` does today? Or we're introducing `--dry-run` as a guinea pig so we see how users react and then decide how the ultimate `verify` UX is going to be?

**Comment by marcosnils** [comment]
> Added a `Skipped` state, WDYT?
> 
> >

Loved it. Ship it :ship:
