### PR TITLE
fix(core): ensure `directory.Stat()` and `file.Stat()` can access the `BuildkitSession`

### LINKED ISSUE #11667: 🐞 0.19.9 regression pulling from pkg.dev - token based
### What is the issue?

¡Hola! Starting version 0.19.9 my pipeling pulling from GCP's pkg.dev started to fail.

0.19.9 output    
```
      │ │ ╰╴$ 4dffc0a93cac759f Container@xxh3:6142b3636448fd5f.from(
      │ │   │ ┆ address: "us-east4-docker.pkg.dev/chapauy-20251216/prod/data:latest@sha256:5104aa2c7264732002383a4d51cc8234cb4666773c9d4e770dba906718f7df1a"
      │ │   │ ): Container! = xxh3:b394e37c28b0735c 0.0s CACHED
      │ │   ├╴✔ 2bed6ad3d1d9c928 resolving us-east4-docker.pkg.dev/chapauy-20251216/prod/data:latest@sha256:5104aa2c7264732002383a4d51cc8234cb4666773c9d4e770dba906718f7df1a 0.0s
      │ │   ╰╴$ 13bf4bd0ac096592 pull us-east4-docker.pkg.dev/chapauy-20251216/prod/data:latest@sha256:5104aa2c7264732002383a4d51cc8234cb4666773c9d4e770dba906718f7df1a 0.0s CACHED
      │ ╰╴✘ aefb9b915afd7468 .directory(path: "/app/db"): Directory! = xxh3:b02c17d326edf48e 0.3s ERROR
      │   ! failed to copy: httpReadSeeker: failed open: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://us-east4-
      │     docker.pkg.dev/v2/token?scope=repository%3Achapauy-20251216%2Fprod%2Fdata%3Apull&service=us-east4-docker.pkg.dev: 403 Forbidden
      │   ╰╴✘ 8b8a0b4c1efac1ac remotes.docker.resolver.FetchToken 0.3s ERROR
 ```
vs 0.19.8:
```
      │ │ ╰╴✔ 81ed18d1b64dc4b0 Container@xxh3:6142b3636448fd5f.from(
      │ │   │ ┆ address: "us-east4-docker.pkg.dev/chapauy-20251216/prod/data:latest@sha256:5104aa2c7264732002383a4d51cc8234cb4666773c9d4e770dba906718f7df1a"
      │ │   │ ): Container! = xxh3:b394e37c28b0735c 0.0s
      │ │   ├╴✔ 06d07a7fb93e586a resolving us-east4-docker.pkg.dev/chapauy-20251216/prod/data:latest@sha256:5104aa2c7264732002383a4d51cc8234cb4666773c9d4e770dba906718f7df1a 0.0s
      │ │   ╰╴✔ f099930a61eb692c pull us-east4-docker.pkg.dev/chapauy-20251216/prod/data:latest@sha256:5104aa2c7264732002383a4d51cc8234cb4666773c9d4e770dba906718f7df1a 0.0s
      │ ├╴✔ 68a6fea2f84043e3 .directory(path: "/app/db"): Directory! = xxh3:b02c17d326edf48e 22.3s
      │ │ ├╴✔ 3f203d03e0262ac8 remotes.docker.resolver.HTTPRequest 0.3s
      │ │ │ ╰╴✔ 0b16476e61c36555 HTTP GET 0.3s
```

Work around was easy (pin 0.19.8 as version) https://github.com/jcodagnone/chapauy/commit/0b5de4d30b1904b95ad918a10e1341d387f7041e

https://github.com/jcodagnone/chapauy/blob/master/.dagger/main.go#L166
```
	// 1. Get latest Data image
	dataCtr := dag.Container().
		WithRegistryAuth(infra.Images.RegistryAddr, "oauth2accesstoken", tokenSecret).
		From(infra.Images.Data)
```

"vibecoded" two possible solutions, but I was unable to verify them `hack/with-dev` yet, but meanwhile the report might be useful for others. 

```
Author: Juan F. Codagnone <jcodagnone@gmail.com>
Date:   Mon Jan 12 10:33:14 2026 -0300

    fix(auth): retry credential lookup without port if initial lookup fails
    
    This fixes a regression introduced in commit c9df98d956f46faf835b82f692eac98a90933347 ("upgrade to containerd v2 (#11337)") where authentication fails for registries when the host string includes a port (e.g., from containerd v2), but the credential helper expects the hostname without a port.
    
    The fix attempts to strip the port and retry the lookup if no credentials are found initially.

diff --git a/internal/buildkit/session/auth/authprovider/authprovider.go b/internal/buildkit/session/auth/authprovider/authprovider.go
index fa1585c76..52bc66abb 100644
--- a/internal/buildkit/session/auth/authprovider/authprovider.go
+++ b/internal/buildkit/session/auth/authprovider/authprovider.go
@@ -8,6 +8,7 @@ import (
        "crypto/tls"
        "crypto/x509"
        "fmt"
+       "net"
        "os"
        "runtime"
        "strconv"
@@ -249,6 +250,17 @@ func (ap *authProvider) getAuthConfig(host string) (*types.AuthConfig, error) {
                if err != nil {
                        return nil, err
                }
+
+               if ac.Username == "" && ac.Password == "" && ac.IdentityToken == "" && ac.RegistryToken == "" {
+                       hostname, port, err := net.SplitHostPort(host)
+                       if err == nil && port != "" {
+                               ac2, err := ap.config.GetAuthConfig(hostname)
+                               if err == nil && (ac2.Username != "" || ac2.Password != "" || ac2.IdentityToken != "" || ac2.RegistryToken != "") {
+                                       ac = ac2
+                               }
+                       }
+               }
+
                ap.authConfigCache[host] = &ac
        }
```

```
commit e6c4742e5a04f08db48f3ec09198206e6e5591b7 (HEAD -> xx)
Author: Juan F. Codagnone <jcodagnone@gmail.com>
Date:   Mon Jan 12 11:31:47 2026 -0300

    auth: implement FetchToken in RegistryAuthProvider
    
    This commit implements the FetchToken method in RegistryAuthProvider, which was missing and caused a regression in v0.19.9 when using token-based authentication (e.g., GCP Artifact Registry).
    
    The regression was introduced in commit 8c6516e325 (Sep 17, 2025), which internalized Buildkit dependencies and exposed the missing implementation.
    
    This fix ports the FetchToken logic from Buildkit's internal auth provider, enabling proper OAuth token exchange using the credentials stored in RegistryAuthProvider.

diff --git a/auth/registry.go b/auth/registry.go
index 04cb8b014..39f702391 100644
--- a/auth/registry.go
+++ b/auth/registry.go
@@ -2,10 +2,16 @@ package auth
 
 import (
        "context"
+       "errors"
        "fmt"
+       "net/http"
        "strconv"
        "strings"
        "sync"
+       "time"
+
+       authutil "github.com/containerd/containerd/v2/core/remotes/docker/auth"
+       remoteserrors "github.com/containerd/containerd/v2/core/remotes/errors"
 
        bkauth "github.com/dagger/dagger/internal/buildkit/session/auth"
        "google.golang.org/grpc"
@@ -182,3 +188,70 @@ func (r *RegistryAuthProvider) Credentials(ctx context.Context, req *bkauth.Cred
        }
        return nil, status.Errorf(codes.NotFound, "no credential found for %s", req.GetHost())
 }
+
+func (r *RegistryAuthProvider) FetchToken(ctx context.Context, req *bkauth.FetchTokenRequest) (rr *bkauth.FetchTokenResponse, err error) {
+       creds := r.credential(req.Host)
+       if creds == nil {
+               creds = &bkauth.CredentialsResponse{}
+       }
+
+       to := authutil.TokenOptions{
+               Realm:    req.Realm,
+               Service:  req.Service,
+               Scopes:   req.Scopes,
+               Username: creds.Username,
+               Secret:   creds.Secret,
+       }
+
+       httpClient := http.DefaultClient
+       // TODO: support TLS config if needed, similar to Buildkit's auth provider
+       // if tc, err := ap.tlsConfig(req.Host); err == nil && tc != nil {
+       //      transport := http.DefaultTransport.(*http.Transport).Clone()
+       //      transport.TLSClientConfig = tc
+       //      httpClient.Transport = transport
+       // }
+
+       if creds.Secret != "" {
+               // credential information is provided, use oauth POST endpoint
+               resp, err := authutil.FetchTokenWithOAuth(ctx, httpClient, nil, "dagger-buildkit-client", to)
+               if err != nil {
+                       var errStatus remoteserrors.ErrUnexpectedStatus
+                       if errors.As(err, &errStatus) {
+                               // Registries without support for POST may return 404 for POST /v2/token.
+                               // As of September 2017, GCR is known to return 404.
+                               // As of February 2018, JFrog Artifactory is known to return 401.
+                               if (errStatus.StatusCode == 405 && to.Username != "") || errStatus.StatusCode == 404 || errStatus.StatusCode == 401 {
+                                       resp, err := authutil.FetchToken(ctx, httpClient, nil, to)
+                                       if err != nil {
+                                               return nil, err
+                                       }
+                                       return toTokenResponse(resp.Token, resp.IssuedAt, int64(resp.ExpiresInSeconds)), nil
+                               }
+                       }
+                       return nil, err
+               }
+               return toTokenResponse(resp.AccessToken, resp.IssuedAt, int64(resp.ExpiresInSeconds)), nil
+       }
+       // do request anonymously
+       resp, err := authutil.FetchToken(ctx, httpClient, nil, to)
+       if err != nil {
+               return nil, fmt.Errorf("failed to fetch anonymous token: %w", err)
+       }
+       return toTokenResponse(resp.Token, resp.IssuedAt, int64(resp.ExpiresInSeconds)), nil
+}
+
+func (r *RegistryAuthProvider) GetTokenAuthority(ctx context.Context, req *bkauth.GetTokenAuthorityRequest) (*bkauth.GetTokenAuthorityResponse, error) {
+       return nil, status.Errorf(codes.Unimplemented, "GetTokenAuthority not implemented")
+}
+
+func (r *RegistryAuthProvider) VerifyTokenAuthority(ctx context.Context, req *bkauth.VerifyTokenAuthorityRequest) (*bkauth.VerifyTokenAuthorityResponse, error) {
+       return nil, status.Errorf(codes.Unimplemented, "VerifyTokenAuthority not implemented")
+}
+
+func toTokenResponse(token string, issuedAt time.Time, expires int64) *bkauth.FetchTokenResponse {
+       return &bkauth.FetchTokenResponse{
+               Token:            token,
+               IssuedAt:         issuedAt.Unix(),
+               ExpiresInSeconds: expires,
+       }
+}

```

### Dagger version

dagger v0.19.9 (image://registry.dagger.io/engine:v0.19.9) linux/amd64

### Steps to reproduce

_No response_

### Log output

_No response_

### PR DESCRIPTION
**Pull request by grouville**
Fixes #11667 (attempt)

## Context 

After investigation of above issue, it seems that PR https://github.com/dagger/dagger/pull/11403 has introduced a regression when dagify-ing the `Directory` and `File` operations from BuildKit.

The confirmed theory is :
> - Before (v0.19.8): Directory.Directory() used StatLLB → bk.Solve() → proper session handling
> - After (v0.19.9): Directory.Directory() uses new Stat() → MountRef(ctx, immutableRef, nil, ...) → nil session

### What happened
The regression happened due to some uncovered test cases regarding the manipulation of artifacts coming from private registries.

As you can see below, the _actual full chain of events leading to the bug are very hard / impossible to anticipate_:
```markdown
1. `Directory.Directory("/app/db")` calls `dir.Stat(ctx, srv, ".", false)`
2. `Stat()` calls `MountRef(ctx, immutableRef, nil, ...)` with a hardcoded `nil` session
3. `ref.Mount(ctx, readonly, nil)` → `Extract(ctx, nil) → unlazy(ctx, ..., nil, ...)`
4. `lazyRefProvider{session: nil}` → `Provider(nil)` → Resolver with nil session
5. `CredentialsFunc(sm, nil)` → `sm.Any(ctx, nil, ...)` returns immediately (nil check)
6. Returns empty credentials `("", "", "", nil)`
7. Authorizer created with empty credentials → anonymous token fetch → 403 Forbidden
```

Basically, those operations, when `stating`, need to be able to access the auth informations, only accessible if a buildkit session is present

##### TODO
- [x] integration test
- [Manual repro](https://github.com/dagger/dagger/issues/11667#issuecomment-3740243559)
- [x] Other operations might be impacted apart file and Directory

### CODE REVIEW

File: core/util.go [hunk 1]
```diff
@@ -287,6 +287,7 @@ func mountRefAsReadOnly(opt *mountRefOpt) {
 // To simplify external logic, when the ref is nil, i.e. scratch, the callback
 // just receives a tmpdir that gets deleted when the function completes.
 func MountRef(ctx context.Context, ref bkcache.Ref, g bksession.Group, f func(string, *mount.Mount) error, optFns ...mountRefOptFn) error {
+	fmt.Fprintf(os.Stderr, "🔍 MountRef called: sessionGroup isNil=%v\n", g == nil)
```
Comment (marcosnils) [inline core/util.go]:
```suggestion
```

File: internal/buildkit/session/group.go [hunk 2]
```diff
@@ -54,6 +56,7 @@ func AllSessionIDs(g Group) (out []string) {
 
 func (sm *Manager) Any(ctx context.Context, g Group, f func(context.Context, string, Caller) error) error {
 	if g == nil {
+		fmt.Fprintf(os.Stderr, "🔍 session.Manager.Any: group is nil, returning without fetching credentials!\n")
```
Comment (marcosnils) [inline internal/buildkit/session/group.go]:
```suggestion
```

File: core/directory.go [hunk 3]
```diff
@@ -1608,6 +1608,21 @@ func (dir *Directory) Stat(ctx context.Context, srv *dagql.Server, targetPath st
...
+	bkSessionGroup, ok := buildkit.CurrentBuildkitSessionGroup(ctx)
+	if !ok {
+		query, err := CurrentQuery(ctx)
+		if err == nil {
+			bk, err := query.Buildkit(ctx)
+			if err == nil {
+				bkSessionGroup = buildkit.NewSessionGroup(bk.ID())
+			}
+		}
+	}
```
Comment (marcosnils) [inline core/directory.go]: can it actually happen at this stage that we don't have a session group?

**Comment by sipsma** [comment]
just a note that I've seen some flakes in CI with the error `no active sessions` (e.g. [here](https://dagger.cloud/dagger/checks/github.com/dagger/dagger@408026ff81bf33d42da478cbbf8186d53d8e42ee?check=testSplit%3AtestModules&listen=7f0347f15c1665c4&listen=c8e5462504bf674a&listen=df933926e086c1ca&listen=5dcaf19b63c614aa#c179122179894dfb)), wondering if it's the same root cause as is fixed here

File: core/file.go [hunk 4]
```diff
@@ -500,6 +500,21 @@ func (file *File) StatDagOp(ctx context.Context, srv *dagql.Server) (*Stat, erro
 		return nil, err
 	}
 
+	// Session is needed for registry auth when fetching uncached blobs.
+	// Context has session when called via DagOpWrapper, but Stat() is also called
+	// internally (e.g., from File.File()) bypassing the schema layer.
+	// Fall back to buildkit client's session for those internal paths.
+	bkSessionGroup, ok := buildkit.CurrentBuildkitSessionGroup(ctx)
```
Comment (alexcb) [inline core/file.go]: nit: duplicate code.

maybe move this code (and the similar code from core/directory.go) to a helper function under core/util.go

Comment (sipsma) [reply core/file.go]: +1, might even make sense to just put the fallback `!ok` logic right in `buildkit.CurrentBuildkitSessionGroup` ?

File: core/directory.go (hunk 3 above)
Comment (grouville) [reply core/directory.go]: Yes, when loading a module, some operations are outside the dagop context and early returning leads to failures

File: core/file.go (hunk 4 above)
Comment (grouville) [reply core/file.go]: Done 🙏

**Comment by grouville** [comment]
Just fixed a linter issue
