### PR TITLE
avoids starting service twice when used by different clients

### LINKED ISSUE #11014: 🐞 Services are not de-duplicated correctly
### What is the issue?

Mounting a service into another container before returning it, creates 2 instances of the service in the engine, and the exposed tunnel moves intermittently between instances of the same service.

For more context:
https://discord.com/channels/707636530424053791/1414607480117530656

### Dagger version

0.18.3

### Steps to reproduce

```golang
func (m *Tests) ServiceTest(ctx context.Context) (*dagger.Service, error) {
        // Define a database service
    db := dag.
        Container().
        From("postgres:14").
        WithExposedPort(5432).
        WithEnvVariable("POSTGRES_PASSWORD", "postgres").
        AsService(dagger.ContainerAsServiceOpts{
            UseEntrypoint: true,
        })

        // Initialize some schema in the database
    init, err := dag.Container().From("postgres:14").
        WithEnvVariable("CACHE_BUSTER", time.Now().String()).
        WithServiceBinding("db", db).
        WithEnvVariable("PGPASSWORD", "postgres").
        WithEnvVariable("PG_HOST", "db").
        WithExec([]string{"sh", "-c", "psql -h db -U postgres -c 'CREATE TABLE test (id SERIAL PRIMARY KEY, name TEXT)'"}).
        WithExec([]string{"echo", "Database is ready: %s", time.Now().String()}).
        Stdout(ctx)
    if err != nil {
        return nil, err
    }
    fmt.Println("Initialized: " + init)

        // Return the service
    return db, nil
}
```
Then, expose the service with the CLI:
```
dagger call service-test up
```
And try to hit the database querying for that table just created:
```
$> psql -h 127.0.0.1 -U postgres -d postgres -c "SELECT * FROM test;"
 id | name
----+------
(0 rows)

$> psql -h 127.0.0.1 -U postgres -d postgres -c "SELECT * FROM test;"
ERROR:  relation "test" does not exist
LINE 1: SELECT * FROM test;
```

### Log output

_No response_

### PR DESCRIPTION
**Pull request by marcosnils**
this commit fixes the issue where running `dagger call svc up` only runs
the service once even if used by different clients.

Fixes #11014

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

File: core/integration/services_test.go [hunk 1]
```diff
@@ -644,6 +644,76 @@ func (m *Caller) Run(ctx context.Context) error {
...
+		WithEnvVariable("CACHE", time.Now().String()).
+		WithExec([]string{"truncate", "-s", "0", "/cache/svc.txt"}).Sync(ctx)
+
+	svc := dag.Container().From("alpine").
+		WithMountedCache("/cache", svcCache).
+		WithExposedPort(8080, dagger.ContainerWithExposedPortOpts{ExperimentalSkipHealthcheck: true}).
+		WithDefaultArgs([]string{"sh", "-c", "echo started >> /cache/svc.txt && while true; do wc -l /cache/svc.txt && sleep 5; done"}).
+		AsService()
+
+	dag.Starter().Start(ctx, svc)
```
Comment (jedevc) [inline core/integration/services_test.go:700]: I'm guessing we need to do this to simulate starting it from another client (in this case a module)?

Because this is a bit of a tricky test case, I'd make sure it's annotated, while I can remember how it works *now*, that probably won't stay the case :sweat_smile:

File: core/service.go [hunk 2]
```diff
@@ -777,7 +777,7 @@ func (svc *Service) startTunnel(ctx context.Context) (running *RunningService, r
 		return nil, fmt.Errorf("failed to get buildkit client: %w", err)
 	}
 
-	upstream, err := svcs.Start(svcCtx, svc.TunnelUpstream.ID(), svc.TunnelUpstream.Self(), true)
+	upstream, err := svcs.Start(svcCtx, svc.TunnelUpstream.ID(), svc.TunnelUpstream.Self(), svc.TunnelUpstream.Self().TunnelUpstream.Self() != nil)
```
Comment (jedevc) [inline core/service.go:780]: we love a one-line fix.
