### PR TITLE
Fix utf8 labels causing hang, clean up + fix label collection in general

### LINKED ISSUE #5627: 🐞 When labels contain UTF8 characters, running any v0.8.2 SDK & CLI hangs while establishing a connection to Engine
### What is the issue?

When certain git commit properties (e.g. author name) contain UTF8 characters, running via SDK & CLI hangs:
image

For example, this happens **consistently** in our CI for all checks in this commit in the `main` branch: https://github.com/dagger/dagger/commit/4bbe077865bc566a53e955c7b0d028a8bf9d447c FTR: https://github.com/dagger/dagger/pull/5610#issuecomment-1677234462

It **does not** happen in the following commit: https://github.com/dagger/dagger/commit/3c8ac3228b5fd232e33fd59933b27a4822d9c54a

But then it happens **consistently** in every job running Dagger in a follow-up PR: https://github.com/dagger/dagger/pull/5624#issuecomment-1677241322

We (+@vito) have narrowed it down to https://github.com/dagger/dagger/pull/5602/files#diff-375c41f6a94e797edee687b8fa151865e2192d8aa9088acaffa174d0de2c3578R217. Commenting that code & re-running against the dev Engine fixes the hanging behaviour.

### Log output

<details>
<summary>Triggered a core dump via <code>SIGQUIT</code> for the <code>dagger session</code> process:</summary>
<pre><code>
> ./hack/make engine:lint
+++ dirname ./hack/make
++ cd ./hack/..
++ pwd
+ DAGGER_SRC_ROOT=/Users/gerhard/github.com/dagger/dagger
+ MAGEDIR=/Users/gerhard/github.com/dagger/dagger/internal/mage
+ cd /Users/gerhard/github.com/dagger/dagger/internal/mage
+ exec go run main.go -w /Users/gerhard/github.com/dagger/dagger engine:lint
Creating new Engine session... OK!
Establishing connection to Engine... SIGQUIT: quit
PC=0x7ff81f95a3da m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x2925aa0, 0x2925a60)
	/usr/local/go/src/runtime/sys_darwin.go:502 +0x34 fp=0x7ff7bfefeb58 sp=0x7ff7bfefeb30 pc=0x10567d4
runtime.semasleep(0xffffffffffffffff)
	/usr/local/go/src/runtime/os_darwin.go:66 +0xad fp=0x7ff7bfefebb0 sp=0x7ff7bfefeb58 pc=0x1032c2d
runtime.notesleep(0x2925868)
	/usr/local/go/src/runtime/lock_sema.go:181 +0x85 fp=0x7ff7bfefebe0 sp=0x7ff7bfefebb0 pc=0x100bf25
runtime.mPark()
	/usr/local/go/src/runtime/proc.go:1530 +0x25 fp=0x7ff7bfefec00 sp=0x7ff7bfefebe0 pc=0x103b5c5
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc.go:2561 +0x65 fp=0x7ff7bfefec50 sp=0x7ff7bfefec00 pc=0x103d2a5
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3339 +0x3d fp=0x7ff7bfefec88 sp=0x7ff7bfefec50 pc=0x103f05d
runtime.park_m(0xc000103ba0?)
	/usr/local/go/src/runtime/proc.go:3511 +0x12d fp=0x7ff7bfefecb8 sp=0x7ff7bfefec88 pc=0x103f5ed
runtime.mcall()
	/usr/local/go/src/runtime/asm_amd64.s:452 +0x43 fp=0x7ff7bfefecc8 sp=0x7ff7bfefecb8 pc=0x106a423

goroutine 1 [select]:
runtime.gopark(0xc0004495c8?, 0x2?, 0x91?, 0x6d?, 0xc00044958c?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004493f0 sp=0xc0004493d0 pc=0x1038bf6
runtime.selectgo(0xc0004495c8, 0xc000449588, 0x1c435e0?, 0x0, 0x100abfd?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc000449530 sp=0xc0004493f0 pc=0x1048dbe
github.com/cenkalti/backoff/v4.doRetryNotify[...](0xc000449658?, {0xb8d9158, 0xc0000a9840}, 0x0, {0x0, 0x0?})
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.0/retry.go:112 +0x265 fp=0xc000449620 sp=0xc000449530 pc=0x18c4e25
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0x2058028?, {0xb8d9158?, 0xc0000a9840?}, 0x19?, {0x0?, 0x0?})
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.0/retry.go:61 +0x65 fp=0xc000449678 sp=0xc000449620 pc=0x18c48c5
github.com/cenkalti/backoff/v4.RetryNotify(...)
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.0/retry.go:49
github.com/cenkalti/backoff/v4.Retry(...)
	/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.2.0/retry.go:38
github.com/dagger/dagger/engine/client.Connect({0x2057fb8, 0xc0000480c0}, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc0003d42a0, 0x24}, {0xc0003d42d0, ...}, ...})
	/app/engine/client/client.go:275 +0x1818 fp=0xc000449a98 sp=0xc000449678 pc=0x1b43298
main.EngineSession(0xc000005500?, {0x1ea4407?, 0x4?, 0x4?})
	/app/cmd/dagger/session.go:74 +0x427 fp=0xc000449d68 sp=0xc000449a98 pc=0x1bcabe7
github.com/spf13/cobra.(*Command).execute(0xc000005500, {0xc0000bb980, 0x4, 0x4})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x862 fp=0xc000449ea0 sp=0xc000449d68 pc=0x13c1b82
github.com/spf13/cobra.(*Command).ExecuteC(0x290bca0)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd fp=0xc000449f58 sp=0xc000449ea0 pc=0x13c23fd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/app/cmd/dagger/main.go:96 +0x32 fp=0xc000449f80 sp=0xc000449f58 pc=0x1bc69d2
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc000449fe0 sp=0xc000449f80 pc=0x10387c7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000449fe8 sp=0xc000449fe0 pc=0x106c541

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000090fb0 sp=0xc000090f90 pc=0x1038bf6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000090fe0 sp=0xc000090fb0 pc=0x1038a30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000090fe8 sp=0xc000090fe0 pc=0x106c541
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000091780 sp=0xc000091760 pc=0x1038bf6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000917c8 sp=0xc000091780 pc=0x1023b3e
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000917e0 sp=0xc0000917c8 pc=0x1018d66
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000917e8 sp=0xc0000917e0 pc=0x106c541
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4d0eab1155c59?, 0x1e3322bb?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000091f70 sp=0xc000091f50 pc=0x1038bf6
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x2924680)
	/usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000091fa0 sp=0xc000091f70 pc=0x10219d3
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000091fc8 sp=0xc000091fa0 pc=0x1021fc5
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000091fe0 sp=0xc000091fc8 pc=0x1018d06
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000091fe8 sp=0xc000091fe0 pc=0x106c541
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0x1f258d8?, 0x40?, 0xc1?, 0x2000000020?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000090628 sp=0xc000090608 pc=0x1038bf6
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000907e0 sp=0xc000090628 pc=0x1017da7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000907e8 sp=0xc0000907e0 pc=0x106c541
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:163 +0x45

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000092750 sp=0xc000092730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000927e0 sp=0xc000092750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000927e8 sp=0xc0000927e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 17 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008c750 sp=0xc00008c730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008c7e0 sp=0xc00008c750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008c7e8 sp=0xc00008c7e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 33 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000588750 sp=0xc000588730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005887e0 sp=0xc000588750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005887e8 sp=0xc0005887e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 18 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008cf50 sp=0xc00008cf30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008cfe0 sp=0xc00008cf50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008cfe8 sp=0xc00008cfe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000092f50 sp=0xc000092f30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000092fe0 sp=0xc000092f50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000092fe8 sp=0xc000092fe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000588f50 sp=0xc000588f30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000588fe0 sp=0xc000588f50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000588fe8 sp=0xc000588fe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000093750 sp=0xc000093730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000937e0 sp=0xc000093750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000937e8 sp=0xc0000937e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000589750 sp=0xc000589730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005897e0 sp=0xc000589750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005897e8 sp=0xc0005897e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000093f50 sp=0xc000093f30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000093fe0 sp=0xc000093f50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000093fe8 sp=0xc000093fe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000589f50 sp=0xc000589f30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000589fe0 sp=0xc000589f50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000589fe8 sp=0xc000589fe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000584750 sp=0xc000584730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005847e0 sp=0xc000584750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005847e8 sp=0xc0005847e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00058a750 sp=0xc00058a730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00058a7e0 sp=0xc00058a750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00058a7e8 sp=0xc00058a7e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x4d0ea484d97a8?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000584f50 sp=0xc000584f30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000584fe0 sp=0xc000584f50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000584fe8 sp=0xc000584fe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x4d0ea484d3ba1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008d750 sp=0xc00008d730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008d7e0 sp=0xc00008d750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008d7e8 sp=0xc00008d7e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x4d0ea484d3acf?, 0x3?, 0x19?, 0xd?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000585750 sp=0xc000585730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005857e0 sp=0xc000585750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005857e8 sp=0xc0005857e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x4d0ea484d3b67?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008df50 sp=0xc00008df30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008dfe0 sp=0xc00008df50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008dfe8 sp=0xc00008dfe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 13 [GC worker (idle)]:
runtime.gopark(0x4d0ea484d8a02?, 0x3?, 0x7d?, 0xd3?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000585f50 sp=0xc000585f30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000585fe0 sp=0xc000585f50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000585fe8 sp=0xc000585fe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x2957040?, 0x1?, 0x7b?, 0x2c?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008e750 sp=0xc00008e730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008e7e0 sp=0xc00008e750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008e7e8 sp=0xc00008e7e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x2957040?, 0x1?, 0x7?, 0x1b?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008ef50 sp=0xc00008ef30 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00008efe0 sp=0xc00008ef50 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008efe8 sp=0xc00008efe0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 14 [GC worker (idle)]:
runtime.gopark(0x2957040?, 0x1?, 0x2d?, 0xa3?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000586750 sp=0xc000586730 pc=0x1038bf6
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0005867e0 sp=0xc000586750 pc=0x101aad1
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0005867e8 sp=0xc0005867e0 pc=0x106c541
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 15 [select, locked to thread]:
runtime.gopark(0xc00008f7a8?, 0x2?, 0x72?, 0x8f?, 0xc00008f7a4?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00008f620 sp=0xc00008f600 pc=0x1038bf6
runtime.selectgo(0xc00008f7a8, 0xc00008f7a0, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc00008f760 sp=0xc00008f620 pc=0x1048dbe
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:1000 +0x187 fp=0xc00008f7e0 sp=0xc00008f760 pc=0x1063767
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00008f7e8 sp=0xc00008f7e0 pc=0x106c541
created by runtime.ensureSigM
	/usr/local/go/src/runtime/signal_unix.go:983 +0xbd

goroutine 23 [syscall]:
runtime.sigNoteSleep(0x0)
	/usr/local/go/src/runtime/os_darwin.go:123 +0x1e fp=0xc00011c7a0 sp=0xc00011c768 pc=0x1032f3e
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:149 +0x28 fp=0xc00011c7c0 sp=0xc00011c7a0 pc=0x1068148
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19 fp=0xc00011c7e0 sp=0xc00011c7c0 pc=0x17d1719
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00011c7e8 sp=0xc00011c7e0 pc=0x106c541
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 24 [chan receive]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00011cef8 sp=0xc00011ced8 pc=0x1038bf6
runtime.chanrecv(0xc00003f080, 0x0, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x49d fp=0xc00011cf88 sp=0xc00011cef8 pc=0x1006a9d
runtime.chanrecv1(0x0?, 0x0?)
	/usr/local/go/src/runtime/chan.go:442 +0x18 fp=0xc00011cfb0 sp=0xc00011cf88 pc=0x1006598
main.EngineSession.func1()
	/app/cmd/dagger/session.go:62 +0x31 fp=0xc00011cfe0 sp=0xc00011cfb0 pc=0x1bcb191
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00011cfe8 sp=0xc00011cfe0 pc=0x106c541
created by main.EngineSession
	/app/cmd/dagger/session.go:61 +0x1b0

goroutine 25 [syscall]:
syscall.syscall(0xc000598000?, 0x0?, 0x800000?, 0x7ffff800000?)
	/usr/local/go/src/runtime/sys_darwin.go:23 +0x7f fp=0xc00011d560 sp=0xc00011d4d0 pc=0x1068aff
syscall.read(0xc00003e0c0?, {0xc00059c000?, 0x1c72aa0?, 0x1010000000000?})
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1209 +0x49 fp=0xc00011d5a0 sp=0xc00011d560 pc=0x1081069
syscall.Read(...)
	/usr/local/go/src/syscall/syscall_unix.go:178
internal/poll.ignoringEINTRIO(...)
	/usr/local/go/src/internal/poll/fd_unix.go:794
internal/poll.(*FD).Read(0xc00003e0c0?, {0xc00059c000?, 0x2000?, 0x2000?})
	/usr/local/go/src/internal/poll/fd_unix.go:163 +0x2ce fp=0xc00011d638 sp=0xc00011d5a0 pc=0x10abdae
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc000012010, {0xc00059c000?, 0x0?, 0x0?})
	/usr/local/go/src/os/file.go:118 +0x5e fp=0xc00011d690 sp=0xc00011d638 pc=0x10b617e
io.discard.ReadFrom({}, {0x204cba0, 0xc000012010})
	/usr/local/go/src/io/io.go:651 +0x72 fp=0xc00011d6e8 sp=0xc00011d690 pc=0x10a4d32
io.(*discard).ReadFrom(0x0?, {0x204cba0?, 0xc000012010?})
	<autogenerated>:1 +0x37 fp=0xc00011d708 sp=0xc00011d6e8 pc=0x10a6bb7
io.copyBuffer({0x204e380, 0x29550a0}, {0x204cba0, 0xc000012010}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:413 +0x14b fp=0xc00011d788 sp=0xc00011d708 pc=0x10a460b
io.Copy(...)
	/usr/local/go/src/io/io.go:386
main.EngineSession.func2()
	/app/cmd/dagger/session.go:68 +0x4f fp=0xc00011d7e0 sp=0xc00011d788 pc=0x1bcb12f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00011d7e8 sp=0xc00011d7e0 pc=0x106c541
created by main.EngineSession
	/app/cmd/dagger/session.go:67 +0x1ff

goroutine 116 [select]:
runtime.gopark(0xc0001e1f80?, 0x2?, 0x10?, 0x1e?, 0xc0001e1f44?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001e1db0 sp=0xc0001e1d90 pc=0x1038bf6
runtime.selectgo(0xc0001e1f80, 0xc0001e1f40, 0x16271e0?, 0x0, 0xc00011e6ff?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc0001e1ef0 sp=0xc0001e1db0 pc=0x1048dbe
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc0000a8ea0, {0x2057f80, 0xc000410640})
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:83 +0x12a fp=0xc0001e1fb8 sp=0xc0001e1ef0 pc=0x1626dca
google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer.func1()
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:55 +0x2e fp=0xc0001e1fe0 sp=0xc0001e1fb8 pc=0x1626ace
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001e1fe8 sp=0xc0001e1fe0 pc=0x106c541
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:55 +0x138

goroutine 51 [IO wait]:
runtime.gopark(0xb?, 0xc00066e000?, 0x0?, 0x13?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001df608 sp=0xc0001df5e8 pc=0x1038bf6
runtime.netpollblock(0x1081069?, 0x10047af?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:527 +0xf7 fp=0xc0001df640 sp=0xc0001df608 pc=0x1031d97
internal/poll.runtime_pollWait(0xa948da8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89 fp=0xc0001df660 sp=0xc0001df640 pc=0x1065e89
internal/poll.(*pollDesc).wait(0xc000184480?, 0xc00066e000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc0001df688 sp=0xc0001df660 pc=0x10aa992
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000184480, {0xc00066e000, 0x1300, 0x1300})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299 fp=0xc0001df720 sp=0xc0001df688 pc=0x10abd79
net.(*netFD).Read(0xc000184480, {0xc00066e000?, 0xc00066e005?, 0xa1?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29 fp=0xc0001df768 sp=0xc0001df720 pc=0x11faaa9
net.(*conn).Read(0xc000642000, {0xc00066e000?, 0x1253c43?, 0xc0006461b0?})
	/usr/local/go/src/net/net.go:183 +0x45 fp=0xc0001df7b0 sp=0xc0001df768 pc=0x120c725
net.(*TCPConn).Read(0xc0001df848?, {0xc00066e000?, 0xc00065e618?, 0x18?})
	<autogenerated>:1 +0x29 fp=0xc0001df7e0 sp=0xc0001df7b0 pc=0x121eca9
crypto/tls.(*atLeastReader).Read(0xc00065e618, {0xc00066e000?, 0xc00065e618?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d fp=0xc0001df828 sp=0xc0001df7e0 pc=0x1257a3d
bytes.(*Buffer).ReadFrom(0xc000646290, {0x2049540, 0xc00065e618})
	/usr/local/go/src/bytes/buffer.go:202 +0x98 fp=0xc0001df880 sp=0xc0001df828 pc=0x1116eb8
crypto/tls.(*Conn).readFromUntil(0xc000646000, {0xab38fc8?, 0xc000642000}, 0x1300?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5 fp=0xc0001df8c0 sp=0xc0001df880 pc=0x1257c25
crypto/tls.(*Conn).readRecordOrCCS(0xc000646000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116 fp=0xc0001dfc20 sp=0xc0001df8c0 pc=0x1255116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc000646000, {0xc00022d000, 0x1000, 0x12dcb80?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f fp=0xc0001dfc90 sp=0xc0001dfc20 pc=0x125b00f
bufio.(*Reader).Read(0xc0002183c0, {0xc000678580, 0x9, 0x12fa805?})
	/usr/local/go/src/bufio/bufio.go:237 +0x1bb fp=0xc0001dfcc8 sp=0xc0001dfc90 pc=0x129299b
io.ReadAtLeast({0x20492a0, 0xc0002183c0}, {0xc000678580, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0x9a fp=0xc0001dfd10 sp=0xc0001dfcc8 pc=0x10a413a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
net/http.http2readFrameHeader({0xc000678580?, 0x9?, 0xc000641aa0?}, {0x20492a0?, 0xc0002183c0?})
	/usr/local/go/src/net/http/h2_bundle.go:1567 +0x6e fp=0xc0001dfd60 sp=0xc0001dfd10 pc=0x12d3a2e
net/http.(*http2Framer).ReadFrame(0xc000678540)
	/usr/local/go/src/net/http/h2_bundle.go:1831 +0x95 fp=0xc0001dfe10 sp=0xc0001dfd60 pc=0x12d4275
net/http.(*http2clientConnReadLoop).run(0xc0001dff98)
	/usr/local/go/src/net/http/h2_bundle.go:9187 +0x12e fp=0xc0001dff60 sp=0xc0001dfe10 pc=0x12f784e
net/http.(*http2ClientConn).readLoop(0xc000644180)
	/usr/local/go/src/net/http/h2_bundle.go:9082 +0x6f fp=0xc0001dffc8 sp=0xc0001dff60 pc=0x12f6d6f
net/http.(*http2Transport).newClientConn.func1()
	/usr/local/go/src/net/http/h2_bundle.go:7779 +0x26 fp=0xc0001dffe0 sp=0xc0001dffc8 pc=0x12ef966
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001dffe8 sp=0xc0001dffe0 pc=0x106c541
created by net/http.(*http2Transport).newClientConn
	/usr/local/go/src/net/http/h2_bundle.go:7779 +0xc3c

goroutine 67 [IO wait]:
runtime.gopark(0x12?, 0xc0001e8000?, 0x0?, 0x80?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00011bd08 sp=0xc00011bce8 pc=0x1038bf6
runtime.netpollblock(0x1081069?, 0x10047af?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:527 +0xf7 fp=0xc00011bd40 sp=0xc00011bd08 pc=0x1031d97
internal/poll.runtime_pollWait(0xa948cb8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89 fp=0xc00011bd60 sp=0xc00011bd40 pc=0x1065e89
internal/poll.(*pollDesc).wait(0xc0001264e0?, 0xc0001e8000?, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc00011bd88 sp=0xc00011bd60 pc=0x10aa992
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001264e0, {0xc0001e8000, 0x8000, 0x8000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299 fp=0xc00011be20 sp=0xc00011bd88 pc=0x10abd79
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc0005b8040, {0xc0001e8000?, 0xc0005a80e0?, 0xffffffffffffffff?})
	/usr/local/go/src/os/file.go:118 +0x5e fp=0xc00011be78 sp=0xc00011be20 pc=0x10b617e
io.copyBuffer({0x2049f20, 0xc0005a80e0}, {0x204cba0, 0xc0005b8040}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:427 +0x1b2 fp=0xc00011bef8 sp=0xc00011be78 pc=0x10a4672
io.Copy(...)
	/usr/local/go/src/io/io.go:386
os/exec.(*Cmd).writerDescriptor.func1()
	/usr/local/go/src/os/exec/exec.go:560 +0x3a fp=0xc00011bf58 sp=0xc00011bef8 pc=0x133efba
os/exec.(*Cmd).Start.func2(0x0?)
	/usr/local/go/src/os/exec/exec.go:717 +0x32 fp=0xc00011bfc8 sp=0xc00011bf58 pc=0x133fd12
os/exec.(*Cmd).Start.func3()
	/usr/local/go/src/os/exec/exec.go:729 +0x2a fp=0xc00011bfe0 sp=0xc00011bfc8 pc=0x133fcaa
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00011bfe8 sp=0xc00011bfe0 pc=0x106c541
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:716 +0xa33

goroutine 115 [select]:
runtime.gopark(0xc0001dbf80?, 0x2?, 0x69?, 0x53?, 0xc0001dbf44?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0001dbdb0 sp=0xc0001dbd90 pc=0x1038bf6
runtime.selectgo(0xc0001dbf80, 0xc0001dbf40, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc0001dbef0 sp=0xc0001dbdb0 pc=0x1048dbe
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc0000a8e40, {0x2057f80, 0xc0004105f0})
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:83 +0x12a fp=0xc0001dbfb8 sp=0xc0001dbef0 pc=0x1626dca
google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer.func1()
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:55 +0x2e fp=0xc0001dbfe0 sp=0xc0001dbfb8 pc=0x1626ace
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0001dbfe8 sp=0xc0001dbfe0 pc=0x106c541
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:55 +0x138

goroutine 69 [IO wait]:
runtime.gopark(0xf?, 0xc00015a000?, 0x0?, 0x80?, 0x0?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0003aab08 sp=0xc0003aaae8 pc=0x1038bf6
runtime.netpollblock(0x1081069?, 0x10047af?, 0x0?)
	/usr/local/go/src/runtime/netpoll.go:527 +0xf7 fp=0xc0003aab40 sp=0xc0003aab08 pc=0x1031d97
internal/poll.runtime_pollWait(0xa948808, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89 fp=0xc0003aab60 sp=0xc0003aab40 pc=0x1065e89
internal/poll.(*pollDesc).wait(0xc0001262a0?, 0xc00015a000?, 0x1)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc0003aab88 sp=0xc0003aab60 pc=0x10aa992
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0001262a0, {0xc00015a000, 0x8000, 0x8000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299 fp=0xc0003aac20 sp=0xc0003aab88 pc=0x10abd79
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc0005b8020, {0xc00015a000?, 0xc0004021c0?, 0x1cdd2a0?})
	/usr/local/go/src/os/file.go:118 +0x5e fp=0xc0003aac78 sp=0xc0003aac20 pc=0x10b617e
github.com/docker/cli/cli/connhelper/commandconn.(*commandConn).Read(0xc000620840, {0xc00015a000?, 0x100d8aa?, 0x10401?})
	/go/pkg/mod/github.com/docker/cli@v24.0.5+incompatible/cli/connhelper/commandconn/commandconn.go:160 +0x2f fp=0xc0003aacb0 sp=0xc0003aac78 pc=0x18d450f
bufio.(*Reader).Read(0xc0001266c0, {0xc0001b43c0, 0x9, 0x30?})
	/usr/local/go/src/bufio/bufio.go:237 +0x1bb fp=0xc0003aace8 sp=0xc0003aacb0 pc=0x129299b
io.ReadAtLeast({0x20492a0, 0xc0001266c0}, {0xc0001b43c0, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0x9a fp=0xc0003aad30 sp=0xc0003aace8 pc=0x10a413a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
golang.org/x/net/http2.readFrameHeader({0xc0001b43c0?, 0x9?, 0xc000428030?}, {0x20492a0?, 0xc0001266c0?})
	/go/pkg/mod/golang.org/x/net@v0.12.0/http2/frame.go:237 +0x6e fp=0xc0003aad80 sp=0xc0003aad30 pc=0x165002e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001b4380)
	/go/pkg/mod/golang.org/x/net@v0.12.0/http2/frame.go:498 +0x95 fp=0xc0003aae30 sp=0xc0003aad80 pc=0x1650875
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0004f5680, 0xc000732000?)
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/transport/http2_client.go:1595 +0x257 fp=0xc0003aafc0 sp=0xc0003aae30 pc=0x16895d7
google.golang.org/grpc/internal/transport.newHTTP2Client.func11()
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/transport/http2_client.go:397 +0x2a fp=0xc0003aafe0 sp=0xc0003aafc0 pc=0x167ef4a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0003aafe8 sp=0xc0003aafe0 pc=0x106c541
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/transport/http2_client.go:397 +0x1e0a

goroutine 70 [select]:
runtime.gopark(0xc00026df00?, 0x2?, 0x88?, 0xdd?, 0xc00026ded4?)
	/usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00026dd60 sp=0xc00026dd40 pc=0x1038bf6
runtime.selectgo(0xc00026df00, 0xc00026ded0, 0xc0005b8010?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x7be fp=0xc00026dea0 sp=0xc00026dd60 pc=0x1048dbe
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc00064a2d0, 0x1)
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/transport/controlbuf.go:418 +0x115 fp=0xc00026df30 sp=0xc00026dea0 pc=0x1674a95
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0002431f0)
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/transport/controlbuf.go:552 +0x91 fp=0xc00026df90 sp=0xc00026df30 pc=0x1675211
google.golang.org/grpc/internal/transport.newHTTP2Client.func6()
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/transport/http2_client.go:451 +0x85 fp=0xc00026dfe0 sp=0xc00026df90 pc=0x167ee25
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00026dfe8 sp=0xc00026dfe0 pc=0x106c541
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/transport/http2_client.go:449 +0x23dc

rax    0x104
rbx    0xba93600
rcx    0x7ff7bfefe9e8
rdx    0x1c00
rdi    0x2925aa0
rsi    0x200100002100
rbp    0x7ff7bfefea90
rsp    0x7ff7bfefe9e8
r8     0x0
r9     0xa0
r10    0x0
r11    0x246
r12    0x16
r13    0x0
r14    0x200100002100
r15    0x1c00
rip    0x7ff81f95a3da
rflags 0x247
cs     0x7
fs     0x0
gs     0x0
Error: paramCh err
exit status 1
</pre></code>
</details>

### Steps to reproduce

```console
gh pr checkout 5624
./hack/make engine:lint
```

### SDK version

Go SDK v0.8.2

### OS version

SDK / CLI on macOS 12.6 & Engine on NixOS 22.11 (Linux 5.15)

### PR DESCRIPTION
**Pull request by vito**
3 changes:

* Log a `--debug` message in the connection retry loop to make it easier to troubleshoot hangs.
* Base64-encode client metadata so fancy UTF8 letters don't cause errors
* Fix/clean up label collection flow to make more sense with the new architecture
  * Fix weird server-global label cache, which really shouldn't have been there anymore, and was probably causing the first connection's labels to be used for all subsequent connections.
  * Rather than putting the root labels into every single object, just let it stay on the root Group. the telemetry progrock.Writer also turns these into labels sent to Cloud, so we don't need to duplicate them anymore.

As a result of that last change, all IDs should now be much smaller, since they don't have to contain the root pipeline + labels. :tada: 

fixes #5627

### CODE REVIEW

**Comment by vito** [comment]
ID size comparison, for the curious:

```shell
❯ echo '{ directory { id } }' | with-dev ./bin/dagger query --progress=plain
1: connect
1: > in init
1: starting engine 
1: starting engine [0.08s]
Connected to engine 6ebbff6c3940 (version devel ())
1: starting session 
1: starting session [0.01s]
1: connect DONE
{
    "directory": {
        "id": "eyJsbGIiOm51bGwsImRpciI6Ii8iLCJwbGF0Zm9ybSI6eyJhcmNoaXRlY3R1cmUiOiJhbWQ2NCIsIm9zIjoibGludXgifSwicGlwZWxpbmUiOltdfQ=="
    }
}
~/src/dagger labels-cleanup ≡
❯ echo '{ directory { id } }' | dagger-0.8.2 query --progress=plain
Connected to engine 648e31eb9036 (version v0.8.2)
{
    "directory": {
        "id": "eyJsbGIiOm51bGwsImRpciI6Ii8iLCJwbGF0Zm9ybSI6eyJhcmNoaXRlY3R1cmUiOiJhbWQ2NCIsIm9zIjoibGludXgifSwicGlwZWxpbmUiOlt7Im5hbWUiOiIiLCJsYWJlbHMiOlt7Im5hbWUiOiJkYWdnZXIuaW8vZ2l0LnJlbW90ZSIsInZhbHVlIjoiZ2l0aHViLmNvbS92aXRvL2RhZ2dlciJ9LHsibmFtZSI6ImRhZ2dlci5pby9naXQucmVmIiwidmFsdW
UiOiIxZDUwN2JkMWZjZWE2OGQyOTM0ZWVjMzhjNTNlYzkyN2UzNDNjNzcyIn0seyJuYW1lIjoiZGFnZ2VyLmlvL2dpdC5hdXRob3IubmFtZSIsInZhbHVlIjoiQWxleCBTdXJhY2kifSx7Im5hbWUiOiJkYWdnZXIuaW8vZ2l0LmF1dGhvci5lbWFpbCIsInZhbHVlIjoiYWxleEBkYWdnZXIuaW8ifSx7Im5hbWUiOiJkYWdnZXIuaW8vZ2l0LmNvbW1pdHRlci5uYW1lIiwidmFsdWU
iOiJBbGV4IFN1cmFjaSJ9LHsibmFtZSI6ImRhZ2dlci5pby9naXQuY29tbWl0dGVyLmVtYWlsIiwidmFsdWUiOiJhbGV4QGRhZ2dlci5pbyJ9LHsibmFtZSI6ImRhZ2dlci5pby9naXQudGl0bGUiLCJ2YWx1ZSI6IndpcDogbGFiZWxzIGNsZWFudXAifSx7Im5hbWUiOiJkYWdnZXIuaW8vZ2l0LmJyYW5jaCIsInZhbHVlIjoibGFiZWxzLWNsZWFudXAifSx7Im5hbWUiOiJkYWdn
ZXIuaW8vZW5naW5lIiwidmFsdWUiOiI2NDhlMzFlYjkwMzYifV19XX0="
    }
}
```

File: engine/opts.go [hunk 1]
```diff
@@ -72,7 +73,10 @@ func (m ClientMetadata) ToGRPCMD() metadata.MD {
 	if err != nil {
 		panic(err)
 	}
-	return metadata.Pairs(clientMetadataMetaKey, string(b))
+	return metadata.Pairs(
+		clientMetadataMetaKey,
+		base64.StdEncoding.EncodeToString(b),
```
Comment (sipsma) [inline engine/opts.go:78]: LGTM but IIUC the same problem might apply to the other opt structs here (`LocalImportOpts` and `LocalExportOpts`, e.g. if a path name on the host being imported/exported is `/🐈/🎅/🤡`), so worth throwing in the same thing for them.

Comment (sipsma) [reply engine/opts.go:78]: Also probably worth extending the integ test added the other day w/ coverage for UTF8 chars in the labels

Comment (vito) [reply engine/opts.go:78]: Looking at `LocalImportOpts` now, I can see that we also have to set some Buildkit-compatible headers to raw values:

https://github.com/dagger/dagger/blob/30e48293b2a287aca3957482ebb71150fb975df4/engine/opts.go#L126-L130

I'll at least change it to use the same code + pattern for anywhere that we're `json.Marshal`ing, but it seems like there's still a timebomb here. Seems unlikely at least, and it would affect Buildkit too.

**Review by sipsma — APPROVED** [review]
Code LGTM, I'm not sure why the rust/elixer tests are failing... but tentative approval for once those are fixed.

**Comment by gerhard** [comment]
Rust failure:
- https://github.com/dagger/dagger/pull/5626 (rebase should fix it)

Elixir failures:
- I think that the [`Cannot connect to Dagger engine` errors](https://github.com/dagger/dagger/actions/runs/5867652125/job/15908780544?pr=5628#step:4:1913) & [`context deadline exceeded` error](https://github.com/dagger/dagger/actions/runs/5867652125/job/15908780544?pr=5628#step:4:2205) are fixed by this PR
- I am not sure about the [base64 decode errors](https://github.com/dagger/dagger/actions/runs/5867652125/job/15908780544?pr=5628#step:4:2098). Could it be changes introduced this PR @wingyplus?

**Comment by gerhard** [comment]
I have confirmed that the `foobar` error is an expected failure, just a red herring. Will open a separate PR which clarifies that it is expected to fail.

**Comment by gerhard** [comment]
Interestingly, `dagger run ./hack/make sdk:elixir:test` passes locally.

`./hack/make sdk:elixir:test` fails. Attaching the output from `./hack/make sdk:elixir:test 2>&1 | tee PR.sdk.elixir.test.log` 👉 [PR.sdk.elixir.test.log](https://github.com/dagger/dagger/files/12345402/PR.sdk.elixir.test.log)

Will continue digging. cc @wingyplus in case you can spare a look.

**Comment by gerhard** [comment]
I have tracked the `[http2: server: error reading preface from client localhost: rpc error: code = Unknown desc = failed to get client metadata for session call: failed to base64-decode x-dagger-client-metadata: illegal base64 data at input byte 0](https://github.com/dagger/dagger/actions/runs/5867652125/job/15908780544?pr=5628#step:4:908)` issue to https://github.com/dagger/dagger/pull/5628/files#diff-f316292c5c53dd4851fadb4327cbd1a86c2c95a882fb23831433fe17080d602aR92

image

Interestingly, this happens intermittently when running it locally. While I was able to reproduce it on the first run, it passed on the second run. Clearing the cache and trying again.

FWIW, it is the new code that triggers the failure, so this is a genuine failure:
image

**Comment by vito** [comment]
@gerhard The base64 encoding is the change this PR introduces, but I wouldn't expect the SDK to have to implement anything. It seems like a new client is talking to an old server, or vice versa? Should probably be dev <=> dev instead?

**Comment by gerhard** [comment]
I found the issue & pushed a fix - see last commit for more details.

The Engine connection was timing out after `10s` (the default timeout value) and then the SDK would proceed to download the latest stable CLI & re-run. I have 2 questions:
1. @vito can you think of a reason why connecting to the Engine can take more than 10s after this change?
2. @wingyplus would it be more reasonable to fail in that case with a timeout, rather than switch to downloading the latest stable CLI & re-running?

**Review by gerhard — APPROVED** [review]
OK, everything looks good to me! We can handle the remaining questions via follow-ups.

As soon as GitHub Webhooks resume normal operation & DCO check passes, this can go in.

FWIW: https://www.githubstatus.com/incidents/ljhhhw2tplqp
image

**Comment by vito** [comment]
> @vito can you think of a reason why connecting to the Engine can take more than 10s after this change?

No reason that I can think of, after going over each of the changes to be sure. :thinking: Could this be happening in other PRs too?

**Comment by gerhard** [comment]
No, I haven't seen it happen before this change. Leaving it with @wingyplus.

**Comment by wingyplus** [comment]
@gerhard sorry, i fallen to sleep last night and thank for help solving on the issue. I’ll investigating this when I can open my computer. 🙇

**Comment by gerhard** [comment]
Not a problem, thank you! FYI:
- https://github.com/dagger/dagger/pull/5640
