### PR TITLE
fix(core): workspace generator visibility

### LINKED ISSUE #12956: GeneratorGroup.isEmpty returns true before generators are run
## Summary

`Workspace.generators().isEmpty()` returns `true` on a fresh `GeneratorGroup` even when the selected generators would produce non-empty changes.

This appears to be a server-side bug in `GeneratorGroup.isEmpty`, not a workspace include/filtering issue.

## Repro

Use any module with a generator that returns a non-empty `Changeset`, for example [`core/integration/testdata/generators/hello-with-generators`](https://github.com/dagger/dagger/blob/main/core/integration/testdata/generators/hello-with-generators/main.go), where `generate-files` creates `foo`.

From the API, query a fresh group without calling `run()` first:

```go
ws := dag.CurrentWorkspace()
empty, err := ws.Generators().IsEmpty(ctx)
```

Or the equivalent GraphQL shape:

```graphql
{
  currentWorkspace {
    generators {
      isEmpty
    }
  }
}
```

## Expected

`isEmpty` should reflect whether the generators' combined output is empty.

For a group that includes `generate-files`, `isEmpty` should be `false`.

## Actual

`isEmpty` returns `true` for a fresh `GeneratorGroup` before the generators have been executed.

## Root Cause

`Workspace.generators()` returns a `GeneratorGroup` whose `Generator.Changes` fields are still unset.

`GeneratorGroup.IsEmpty()` only checks generators where `g.Changes != nil`:

- `core/generators.go`
- `func (gg *GeneratorGroup) IsEmpty(ctx context.Context) (bool, error)`

So an unrun group falls through and returns `true`.

`groupIsEmpty()` in `core/schema/generators.go` calls that directly.

By contrast, single-generator `Generator.isEmpty` already resolves through `changes.isEmpty`, so the group and single-generator APIs are currently inconsistent.

## Scope

This should affect any fresh `GeneratorGroup`, not just `Workspace.generators()`:

- `Workspace.generators()`
- `Module.generators()`
- `CurrentModule.generators()`

### PR DESCRIPTION
**Pull request by grouville**
Fixes #12956 and supersedes #12961 

## Background

Locally we saw:

- `dagger -c 'current-workspace | generators | run'` takes ~10 minutes (it runs every toolchain generator in the workspace).
- `dagger check generated` on the same workspace finishes in seconds (no generators ran).

That told us the CLI session and the `.dagger` check were seeing different module lists. Tracing `currentWorkspace().generators()` in both contexts revealed the discrepancy:

- The CLI call runs in the CLI client’s session, where all toolchains are served, so it enumerates the full generator tree.
- Once the CLI invokes .dagger, the current client switches to the module session, which only serves `.dagger`

`currentWorkspacePrimaryModules()` still used that session, so workspace APIs run from inside `.dagger` only saw the `.dagger` module.

In other words, `ws.Generators()` inside `.dagger` was still looking at the module’s own session, skipping every toolchain generator even though the workspace was the same.

## What changed

1. Check (`.dagger/main.go`): accept the injected workspace (`ws *dagger.Workspace`) and call `ws.Generators().Run()`, so dagger check generated explicitly asks for the same generator group the CLI sees.

2. Workspace API (`core/schema/workspace.go`): pass the workspace into `currentWorkspacePrimaryModules` and, when present, temporarily switch to the workspace owner’s client via `withWorkspaceClientContext` before calling `CurrentServedDeps`. Workspaces already record their owner’s client ID for filesystem operations; using it here simply reuses the CLI session for module enumeration. When no workspace is provided we leave the context unchanged.

3. Regression test: add a minimal toolchain module to the `hello-with-generators` fixture and a helper that lists `ws.Generators()` from inside `.dagger`. We install the toolchain before calling the helper. On the old engine the helper returned "true" because the module session never saw the toolchain generators; on the patched engine it lists the toolchain generator, proving `.dagger` now shares the CLI’s view.

With these changes dagger check generated once again runs all toolchain generators and the CLI and .dagger view the same workspace.

### CODE REVIEW

File: core/schema/workspace.go [hunk 1]
```diff
@@ -489,7 +489,7 @@ func (s *workspaceSchema) services(
 	},
 ) (*core.UpGroup, error) {
 	include := workspaceIncludePatterns(args.Include)
-	mods, err := currentWorkspacePrimaryModules(ctx)
+	mods, err := currentWorkspacePrimaryModules(ctx, parent)
```
Comment (tiborvass) [inline core/schema/workspace.go]: @grouville I wonder if this means it doesn't work two levels deep (aka are there cases where we would want the grandparent too?)

**Comment by tiborvass** [comment]
The way I test this PR:

`
dagger -m github.com/grouville/dagger@fix/workspace-generator-visibility -c 'engine-dev | playground | with-mounted-directory /src $(git https://github.com/grouville/dagger | ref fix/workspace-generator-visibility | tree) | with-workdir /src | with-exec -- dagger check generated'
`

**Review by tiborvass — APPROVED** [review]

**Review by tiborvass — APPROVED** [review]
