### PR TITLE
fix: fix File cannot export on Windows

### LINKED ISSUE #7558: 🐞 unable to export files with Windows CLI
### What is the issue?

The dagger CLI crashes when trying to export a file in Windows. It looks like exporting a file attempts to do a `chown` and the CLI complains that this is not supported by Windows. 

### Dagger version

dagger v0.11.6 (registry.dagger.io/engine) windows/amd64

### Steps to reproduce

Here is a simple function that reproduces the error on Windows, the error should happen with any function that tries to return a file. 

```
    @function 
    def get_file(self) -> dagger.File:
        return (dag.container()
                .from_("alpine:latest")
                .with_exec(["sh", "-c", "echo test >> test.txt"])
                .file("test.txt")
        )
 ```
 
`dagger call get-file export --path test.txt`

### Log output

```
PS C:\Users\levlaz\git\bugs> dagger call get-file
File evaluated. Use "dagger call get-file --help" to see available sub-commands.
PS C:\Users\levlaz\git\bugs> dagger call get-file export --path test.txt
←[32m✔←[0m ←[35mBugs←[0m.←[1mgetFile←[0m←[2m: File!←[0m ←[2m2.7s←[0m
  ←[32m✔←[0m Container.←[1mfrom←[0m(←[36maddress:←[0m ←[33m"alpine:latest"←[0m)←[2m: Container!←[0m ←[2m0.4s←[0m
←[31m✘←[0m File.←[1mexport←[0m(←[36mpath:←[0m ←[33m"test.txt"←[0m)←[2m: Boolean!←[0m ←[2m0.0s←[0m
←[33m! unexpected closing recv msg: rpc error: code = Unknown desc = failed to chown synctarget dest file C:\Users\levlaz\git\bugs\test.txt: chown C:\Users\levlaz\git\bugs\test.txt: not supported by windows
←[0m  ←[31m✘←[0m export file /test.txt to host test.txt ←[2m0.0s←[0m
  ←[33m! unexpected closing recv msg: rpc error: code = Unknown desc = failed to chown synctarget dest file C:\Users\levlaz\git\bugs\test.txt: chown C:\Users\levlaz\git\bugs\test.txt: not supported by windows
←[0m
Error: response from query: input: container.from.withExec.file.export resolve: unexpected closing recv msg: rpc error: code = Unknown desc = failed to chown synctarget dest file C:\Users\levlaz\git\bugs\test.txt: chown C:\Users\levlaz\git\bugs\test.txt: not supported by windows
```

### PR DESCRIPTION
**Pull request by wingyplus**
The `export` function does `chown` cause Windows crash due to it's unsupported. This commit fixed by skip `chown` operation when running in Windows.

Fixes #7558

### CODE REVIEW

File: engine/client/filesync.go [hunk 1]
```diff
@@ -262,8 +262,10 @@ func (t FilesyncTarget) DiffCopy(stream filesync.FileSend_DiffCopyServer) (rerr
 		return fmt.Errorf("failed to create synctarget dest file %s: %w", finalDestPath, err)
 	}
 	defer destF.Close()
-	if err := destF.Chown(int(t.uid), int(t.gid)); err != nil {
-		return fmt.Errorf("failed to chown synctarget dest file %s: %w", finalDestPath, err)
+	if runtime.GOOS != "windows" {
```
Comment (pjmagee) [inline engine/client/filesync.go:265]: LGTM, I have a broader question on this (I'm still learning go idioms)

in `.NET world` you would have smth like abstract class and maybe `WindowsDriver` or `LinuxDriver` and then delegate to make sure all code in those implementation is unique to that OS but here we are having same execution regardless of OS with if branch.

In go it is possible still to do how I describe or is it more common in golang with this approach?

Comment (wingyplus) [reply engine/client/filesync.go:265]: We can use build constraint to implement chown in specific platforms. 

https://pkg.go.dev/cmd/go#hdr-Build_constraints

**Review by jedevc — APPROVED** [review]
